insert into public.medications (drug,formulation,strength,level_of_care,nhis_status,code,category,eml_page) values
('Adrenaline (Epinephrine)','Injection','1 mg /ml (1:1000)','M','R',NULL,'1.1 General Anaesthetics','15'),
('Adrenaline (Epinephrine)','Injection','100 microgram/ ml (1:10 000)','M','R',NULL,'1.1 General Anaesthetics','15'),
('Atropine','Injection','0.6 mg/ ml','B2','R',NULL,'1.1 General Anaesthetics','15'),
('Atropine','Injection','1 mg/ ml','B2','R',NULL,'1.1 General Anaesthetics','15'),
('Bupivacaine','Injection','0.25% (plain)','C','R',NULL,'1.1 General Anaesthetics','15'),
('Bupivacaine','Injection','0.5% (heavy)','C','R',NULL,'1.1 General Anaesthetics','15'),
('Bupivacaine','Injection','5 mg/ml','C','NR',NULL,'1.1 General Anaesthetics','15'),
('Bupivacaine + Adrenaline','Injection','0.25% + 1:200 000','C','NR',NULL,'1.1 General Anaesthetics','15'),
('Bupivacaine + Adrenaline','Injection','0.5% + 1:200 000','C','NR',NULL,'1.1 General Anaesthetics','15'),
('Diazepam','Injection','5 mg/ ml','M','R',NULL,'1.1 General Anaesthetics','15'),
('Ephedrine Hydrochloride','Injection','50 mg','B2','R',NULL,'1.1 General Anaesthetics','15'),
('Fentanyl','Injection','50 microgram','C','NR',NULL,'1.1 General Anaesthetics','15'),
('Intralipid','Infusion','20%',NULL,'NR',NULL,'1.1 General Anaesthetics','15'),
('Ketamine','Injection','10 mg/ml','B2','R',NULL,'1.1 General Anaesthetics','15'),
('Ketamine','Injection','50 mg/ml','B2','R',NULL,'1.1 General Anaesthetics','15'),
('Lidocaine','Injection','2%','M','R',NULL,'1.1 General Anaesthetics','15'),
('Midazolam','Injection','5 mg/ml','C','R',NULL,'1.1 General Anaesthetics','15'),
('Midazolam','Tablet','15 mg','B2','R',NULL,'1.1 General Anaesthetics','15'),
('Nitrous Oxide: Oxygen','Inhalation','50-50',NULL,'NR',NULL,'1.1 General Anaesthetics','15'),
('Oxygen','Inhalation','(blank)','M','NR',NULL,'1.1 General Anaesthetics','15'),
('Ropivacaine','Injection','7.5 mg/ml','C','R',NULL,'1.1 General Anaesthetics','15'),
('Thiopentone Sodium','Injection','1 g','C','NR',NULL,'1.1 General Anaesthetics','15'),
('Lidocaine','Cream','2%','M','R',NULL,'1.2 Local Anaesthetics','16'),
('Lidocaine','Gel','2%','M','R',NULL,'1.2 Local Anaesthetics','16'),
('Lidocaine','Injection','1%','M','R',NULL,'1.2 Local Anaesthetics','16'),
('Lidocaine','Injection','2%','M','R',NULL,'1.2 Local Anaesthetics','16'),
('Lidocaine','Injection','20 mg/ml','B2','R',NULL,'1.2 Local Anaesthetics','16'),
('Lidocaine','Spray','10%','M','R',NULL,'1.2 Local Anaesthetics','16'),
('Lidocaine + Adrenaline','Injection','10 mg/ml + 5 microgram/ ml','B2','R',NULL,'1.2 Local Anaesthetics','16'),
('Lidocaine + Adrenaline','Injection','20 mg/ml + 5 microgram/ ml','B2','R',NULL,'1.2 Local Anaesthetics','16'),
('Allupurinol','Tablet','100 mg','B1','R',NULL,'2.1 Drugs used in Gout','16'),
('Allupurinol','Tablet','300 mg','B1','R',NULL,'2.1 Drugs used in Gout','16'),
('Colchicine','Tablet','(blank)',NULL,'R',NULL,'2.1 Drugs used in Gout','16'),
('Aspirin','Tablet','300 mg','A','R',NULL,'2.2 Non-Opiod, Non-Steroidal Analgesics','16'),
('Celecoxib','Tablet','100 mg',NULL,'R',NULL,'2.2 Non-Opiod, Non-Steroidal Analgesics','16'),
('Celecoxib','Tablet','200 mg',NULL,'R',NULL,'2.2 Non-Opiod, Non-Steroidal Analgesics','16'),
('Diclofenac','Capsule','75 mg','B1','R',NULL,'2.2 Non-Opiod, Non-Steroidal Analgesics','16'),
('Diclofenac','Gel','1%','M','R',NULL,'2.2 Non-Opiod, Non-Steroidal Analgesics','16'),
('Diclofenac','Injection','25 mg/ml','B1','R',NULL,'2.2 Non-Opiod, Non-Steroidal Analgesics','16'),
('Diclofenac','Spray','(blank)','M','R',NULL,'2.2 Non-Opiod, Non-Steroidal Analgesics','16'),
('Diclofenac','Suppository','100 mg','M','R',NULL,'2.2 Non-Opiod, Non-Steroidal Analgesics','16'),
('Diclofenac','Suppository','50 mg','A','R',NULL,'2.2 Non-Opiod, Non-Steroidal Analgesics','16'),
('Diclofenac','Tablet','50 mg','A','R',NULL,'2.2 Non-Opiod, Non-Steroidal Analgesics','16'),
('Ibuprofen','Suspension','100 mg/5 ml','A','R',NULL,'2.2 Non-Opiod, Non-Steroidal Analgesics','16'),
('Ibuprofen','Tablet','200 mg','A','R',NULL,'2.2 Non-Opiod, Non-Steroidal Analgesics','17'),
('Ibuprofen','Tablet','400 mg','A','R',NULL,'2.2 Non-Opiod, Non-Steroidal Analgesics','17'),
('Indomethacin','Tablet','25 mg',NULL,'R',NULL,'2.2 Non-Opiod, Non-Steroidal Analgesics','17'),
('Indomethacin','Tablet','75 mg',NULL,'R',NULL,'2.2 Non-Opiod, Non-Steroidal Analgesics','17'),
('Mefenamic Acid','Tablet','500 mg',NULL,'R',NULL,'2.2 Non-Opiod, Non-Steroidal Analgesics','17'),
('Naproxen','Tablet (Enteric Coated)','500 mg',NULL,'R',NULL,'2.2 Non-Opiod, Non-Steroidal Analgesics','17'),
('Paracetamol','Injection','10 mg/ml','M','R',NULL,'2.2 Non-Opiod, Non-Steroidal Analgesics','17'),
('Paracetamol','Suppository','125 mg','M','R',NULL,'2.2 Non-Opiod, Non-Steroidal Analgesics','17'),
('Paracetamol','Suppository','250 mg','A','R',NULL,'2.2 Non-Opiod, Non-Steroidal Analgesics','17'),
('Paracetamol','Suppository','500 mg','A','R',NULL,'2.2 Non-Opiod, Non-Steroidal Analgesics','17'),
('Paracetamol','Syrup','120 mg/5 ml','M','R',NULL,'2.2 Non-Opiod, Non-Steroidal Analgesics','17'),
('Paracetamol','Tablet','500 mg','M','R',NULL,'2.2 Non-Opiod, Non-Steroidal Analgesics','17'),
('Codeine','Tablet','15 mg','B2','R',NULL,'2.3 Opioid Analgesics','17'),
('Codeine','Tablet','60 mg','B2','R',NULL,'2.3 Opioid Analgesics','17'),
('Fentanyl','Transdermal patch','(blank)','B2','NR',NULL,'2.3 Opioid Analgesics','17'),
('Morphine Sulphate','Injection','10 mg/ml','B2','R',NULL,'2.3 Opioid Analgesics','17'),
('Morphine Sulphate','Injection (preserva- tive-free)','10 mg/ml','SM','R',NULL,'2.3 Opioid Analgesics','17'),
('Morphine Sulphate','Tablet','10 mg','B2','R',NULL,'2.3 Opioid Analgesics','17'),
('Morphine Sulphate','Tablet (slow release)','30 mg','B2','R',NULL,'2.3 Opioid Analgesics','17'),
('Pethidine','Injection','50 mg/ml','B2','R',NULL,'2.3 Opioid Analgesics','17'),
('Tramadol Hydrochloride','Capsule','50 mg','B2','NR',NULL,'2.3 Opioid Analgesics','17'),
('Tramadol Hydrochloride','Injection','50 mg/ml','B2','NR',NULL,'2.3 Opioid Analgesics','17'),
('Abatacept','Injection','125 mg/ml',NULL,'R',NULL,'2.4 Others','17'),
('Adalimumab','Injection','50 mg/ml',NULL,'R',NULL,'2.4 Others','17'),
('Anakinra','Injection','150 mg/ml',NULL,'R',NULL,'2.4 Others','18'),
('Azathioprine','Injection','25 mg',NULL,'R',NULL,'2.4 Others','18'),
('Azathioprine','Tablet','25 mg',NULL,'R',NULL,'2.4 Others','18'),
('Belimumab','Infusion','120 mg',NULL,'R',NULL,'2.4 Others','18'),
('Belimumab','Infusion','400 mg',NULL,'R',NULL,'2.4 Others','18'),
('Celecoxib','Tablet','200 mg',NULL,'R',NULL,'2.4 Others','18'),
('Certolizumab','Tablet','200 mg/ml',NULL,'R',NULL,'2.4 Others','18'),
('Clonidine','Tablet','(blank)',NULL,'R',NULL,'2.4 Others','18'),
('Cyclophosphamide','Injection','200 mg','D','NR',NULL,'2.4 Others','18'),
('Cyclophosphamide','Injection','500 mg','D','R',NULL,'2.4 Others','18'),
('Cyclophosphamide','Tablet','50 mg','D','NR',NULL,'2.4 Others','18'),
('Cycloserine','Capsule','250 mg',NULL,'R',NULL,'2.4 Others','18'),
('Cyclosporine','Injection','50 mg/ml',NULL,'R',NULL,'2.4 Others','18'),
('Cyclosporine','Oral Solution','100 mg/ml',NULL,'R',NULL,'2.4 Others','18'),
('Cyclosporine','Tablet','10 mg',NULL,'R',NULL,'2.4 Others','18'),
('Cyclosporine','Tablet','25 mg',NULL,'R',NULL,'2.4 Others','18'),
('D-penicillamine','Tablet','125 mg',NULL,'R',NULL,'2.4 Others','18'),
('Etanercept','Injection','50 mg/ml',NULL,'R',NULL,'2.4 Others','18'),
('Gabapentin','Tablet','(blank)',NULL,'R',NULL,'2.4 Others','18'),
('Golimumab','Injection','100 mg/ml',NULL,'R',NULL,'2.4 Others','18'),
('Hydroxychloroquine','Tablet','200 mg',NULL,'R',NULL,'2.4 Others','18'),
('Infliximab','Injection','100 mg',NULL,'R',NULL,'2.4 Others','18'),
('Leflunomide','Tablet','10 mg',NULL,'R',NULL,'2.4 Others','18'),
('Leflunomide','Tablet','100 mg',NULL,'R',NULL,'2.4 Others','18'),
('Leflunomide','Tablet','15 mg',NULL,'R',NULL,'2.4 Others','18'),
('Methocarbamol','Tablet','750 mg',NULL,'R',NULL,'2.4 Others','18'),
('Methotrexate','Tablet','2.5 mg','D','R',NULL,'2.4 Others','18'),
('Methotrexate','Tablet','25 mg/ml','D','R',NULL,'2.4 Others','18'),
('Methylprednisolone','Infusion','(blank)',NULL,'R',NULL,'2.4 Others','18'),
('Minocycline','Capsule (Modified-re- lease)','100 mg',NULL,'R',NULL,'2.4 Others','19'),
('Mycophenolate mofetil','Capsule','250 mg',NULL,'R',NULL,'2.4 Others','19'),
('Mycophenolate mofetil','Injection','500 mg',NULL,'R',NULL,'2.4 Others','19'),
('Mycophenolate mofetil','Suspension','200 mg/ml',NULL,'R',NULL,'2.4 Others','19'),
('Pregabalin','Tablet','(blank)',NULL,'R',NULL,'2.4 Others','19'),
('Rituximab','Injection','10 mg/ml',NULL,'R',NULL,'2.4 Others','19'),
('Rituximab','Injection','119.66 mg/ ml',NULL,'R',NULL,'2.4 Others','19'),
('Sodium Aurothiomalate','Injection','100 mg/ml',NULL,'R',NULL,'2.4 Others','19'),
('Sodium Aurothiomalate','Injection','20 mg/ml',NULL,'R',NULL,'2.4 Others','19'),
('Sulfasalazine','Suspension','50 mg/ml',NULL,'R',NULL,'2.4 Others','19'),
('Sulfasalazine','Tablet','500 mg',NULL,'R',NULL,'2.4 Others','19'),
('Tacrolimus','Injection','5 mg/ml',NULL,'R',NULL,'2.4 Others','19'),
('Tacrolimus','Tablet','2 mg',NULL,'R',NULL,'2.4 Others','19'),
('Tacrolimus','Tablet','5 mg',NULL,'R',NULL,'2.4 Others','19'),
('Tacrolimus','Tablet','500 microgram',NULL,'R',NULL,'2.4 Others','19'),
('Tocilizumab','Injection','180 mg/ml',NULL,'R',NULL,'2.4 Others','19'),
('Tocilizumab','Injection','20 mg/ml',NULL,'R',NULL,'2.4 Others','19'),
('Tofacitinib','Tablet','11 mg',NULL,'R',NULL,'2.4 Others','19'),
('Tofacitinib','Tablet','5 mg',NULL,'R',NULL,'2.4 Others','19'),
('Adrenaline (Epinephrine)','Injection','1 mg /ml (1:1000)','M','R',NULL,'3. Anti-Allergic Drugs','19'),
('Cetirizine','Tablet','10 mg','A','R',NULL,'3. Anti-Allergic Drugs','19'),
('Chlorpheniramine','Syrup','3 mg/5 ml','A','R',NULL,'3. Anti-Allergic Drugs','19'),
('Chlorpheniramine','Tablet','4 mg','A','R',NULL,'3. Anti-Allergic Drugs','19'),
('Dexamethasone','Injection','4 mg/ml','C','R',NULL,'3. Anti-Allergic Drugs','19'),
('Dexamethasone','Tablet','500 microgram','D','R',NULL,'3. Anti-Allergic Drugs','20'),
('Hydrocortisone','Cream','0.5%','B1','R',NULL,'3. Anti-Allergic Drugs','20'),
('Hydrocortisone','Cream','1%','B1','R',NULL,'3. Anti-Allergic Drugs','20'),
('Hydrocortisone','Injection','100 mg','M','R',NULL,'3. Anti-Allergic Drugs','20'),
('Hydrocortisone','Tablet','10 mg','C','NR',NULL,'3. Anti-Allergic Drugs','20'),
('Hydrocortisone','Tablet','20 mg','SM','NR',NULL,'3. Anti-Allergic Drugs','20'),
('Prednisolone','Tablet','5 mg','B1','R',NULL,'3. Anti-Allergic Drugs','20'),
('Promethazine Hydrochloride','Elixir','6 mg/5 ml','A','R',NULL,'3. Anti-Allergic Drugs','20'),
('Promethazine Hydrochloride','Injection','25 mg/ml','B1','R',NULL,'3. Anti-Allergic Drugs','20'),
('Promethazine Hydrochloride','Tablet','25 mg','A','R',NULL,'3. Anti-Allergic Drugs','20'),
('Capreomycin','Tablet','(blank)',NULL,'NR',NULL,'Anti-tuberculous Drugs','20'),
('Cycloserine','Tablet','(blank)',NULL,'NR',NULL,'Anti-tuberculous Drugs','20'),
('Ethambutol','Tablet','100 mg','PM','NR',NULL,'Anti-tuberculous Drugs','20'),
('Ethambutol','Tablet','400 mg','PM','NR',NULL,'Anti-tuberculous Drugs','20'),
('Ethionamide','Tablet','(blank)',NULL,'NR',NULL,'Anti-tuberculous Drugs','20'),
('Isoniazid','Tablet','100 mg','PM','NR',NULL,'Anti-tuberculous Drugs','20'),
('Isoniazid','Tablet','300 mg','PM','NR',NULL,'Anti-tuberculous Drugs','20'),
('Kanamycin','Tablet','(blank)',NULL,'NR',NULL,'Anti-tuberculous Drugs','20'),
('Levofloxacin','Tablet','(blank)',NULL,'NR',NULL,'Anti-tuberculous Drugs','20'),
('Para-aminosalicylic acid','Tablet','(blank)',NULL,'NR',NULL,'Anti-tuberculous Drugs','20'),
('Prothionamide','Tablet','(blank)',NULL,'NR',NULL,'Anti-tuberculous Drugs','20'),
('Pyrazinamide','Tablet','150 mg','PM','NR',NULL,'Anti-tuberculous Drugs','20'),
('Pyrazinamide','Tablet','400 mg','PM','R',NULL,'Anti-tuberculous Drugs','20'),
('Pyridoxine','Tablet','100 mg','B1','R',NULL,'Anti-tuberculous Drugs','21'),
('Pyridoxine','Tablet','50 mg','B1','R',NULL,'Anti-tuberculous Drugs','21'),
('Rifampicin','Tablet','300 mg','PM','NR',NULL,'Anti-tuberculous Drugs','21'),
('Rifampicin + Isoniazid','Tablet','150 mg + 75 mg','PM','NR',NULL,'Anti-tuberculous Drugs','21'),
('Rifampicin + Isoniazid','Tablet','60 mg + 30 mg','PM','NR',NULL,'Anti-tuberculous Drugs','21'),
('Rifampicin + Isoniazid + Ethambutol','Tablet','150 mg + 75 mg + 275 mg','PM','NR',NULL,'Anti-tuberculous Drugs','21'),
('Rifampicin + Isoniazid + Pyrazinamide','Tablet','60 mg + 30 mg + 150 mg','PM','NR',NULL,'Anti-tuberculous Drugs','21'),
('Rifampicin + Isoniazid + Pyrazinamide + Ethambutol','Tablet','150 mg + 75 mg + 400 mg + 275 mg','PM','NR',NULL,'Anti-tuberculous Drugs','21'),
('Streptomycin Sulphate','Injection','1 g','PM','NR',NULL,'Anti-tuberculous Drugs','21'),
('Azithromycin','Capsule','250 mg','C','R',NULL,'Other Anti-bacterial Drugs','21'),
('Azithromycin','Injection','(blank)','C','R',NULL,'Other Anti-bacterial Drugs','21'),
('Azithromycin','Suspension','200 mg/ml','C','R',NULL,'Other Anti-bacterial Drugs','21'),
('Cefixime','Suspension','20 mg/ml',NULL,'R',NULL,'Other Anti-bacterial Drugs','21'),
('Cefixime','Tablet','200 mg',NULL,'R',NULL,'Other Anti-bacterial Drugs','21'),
('Cefotaxime','Injecton','1 g','C','R',NULL,'Other Anti-bacterial Drugs','21'),
('Cefotaxime','Injecton','500 mg','C','R',NULL,'Other Anti-bacterial Drugs','21'),
('Ceftriaxone','Injecton','1 g','C','R',NULL,'Other Anti-bacterial Drugs','21'),
('Ceftriaxone','Injecton','2 g','D','R',NULL,'Other Anti-bacterial Drugs','21'),
('Ceftriaxone','Injecton','250 mg','C','R',NULL,'Other Anti-bacterial Drugs','21'),
('Cefuroxime','Injection','1.5 g','B2','R',NULL,'Other Anti-bacterial Drugs','21'),
('Cefuroxime','Injection','750 mg','B2','R',NULL,'Other Anti-bacterial Drugs','21'),
('Cefuroxime','Suspension','125 mg/5 ml','B2','R',NULL,'Other Anti-bacterial Drugs','21'),
('Cefuroxime','Tablet','125 mg','B2','R',NULL,'Other Anti-bacterial Drugs','21'),
('Cefuroxime','Tablet','250 mg','B2','R',NULL,'Other Anti-bacterial Drugs','21'),
('Chloramphenicol','Injection','1 g','C','R',NULL,'Other Anti-bacterial Drugs','22'),
('Chloramphenicol','Injection','(blank)','C','R',NULL,'Other Anti-bacterial Drugs','22'),
('Ciprofloxacin','Infusion','2 mg/ml','B2','R',NULL,'Other Anti-bacterial Drugs','22'),
('Ciprofloxacin','Tablet','250 mg','B1','R',NULL,'Other Anti-bacterial Drugs','22'),
('Ciprofloxacin','Tablet','500 mg','B1','R',NULL,'Other Anti-bacterial Drugs','22'),
('Clarithromycin','Capsule','250 mg','C','R',NULL,'Other Anti-bacterial Drugs','22'),
('Clarithromycin','Capsule','500 mg','C','R',NULL,'Other Anti-bacterial Drugs','22'),
('Clarithromycin','Suspension','125 mg/ml','C','R',NULL,'Other Anti-bacterial Drugs','22'),
('Clindamycin','Capsule','150 mg','C','R',NULL,'Other Anti-bacterial Drugs','22'),
('Clindamycin','Cream','2%','M','R',NULL,'Other Anti-bacterial Drugs','22'),
('Clindamycin','Gel','1%','M','R',NULL,'Other Anti-bacterial Drugs','22'),
('Clindamycin','Injection','150 mg/ml','C','R',NULL,'Other Anti-bacterial Drugs','22'),
('Clindamycin','Suspension','75 mg/5 ml','C','R',NULL,'Other Anti-bacterial Drugs','22'),
('Co-trimoxazole','Suspension','(200 mg + 40 mg)/5 ml','A','R',NULL,'Other Anti-bacterial Drugs','22'),
('Co-trimoxazole','Tablet','400 mg + 80 mg','A','R',NULL,'Other Anti-bacterial Drugs','22'),
('Doxycycline','Tablet','100 mg','B1','R',NULL,'Other Anti-bacterial Drugs','22'),
('Erythromycin','Syrup','125 mg/5 ml','B1','R',NULL,'Other Anti-bacterial Drugs','22'),
('Erythromycin','Tablet','250 mg','B1','R',NULL,'Other Anti-bacterial Drugs','22'),
('Gentamicin','Injection','40 mg/ml','C','R',NULL,'Other Anti-bacterial Drugs','22'),
('Levofloxacin','Injection','(blank)',NULL,'NR',NULL,'Other Anti-bacterial Drugs','22'),
('Levofloxacin','Tablet','(blank)',NULL,'NR',NULL,'Other Anti-bacterial Drugs','22'),
('Nitrofurantoin','Tablet','100 mg','B2','R',NULL,'Other Anti-bacterial Drugs','22'),
('Norfloxacin','Injection','(blank)',NULL,'R',NULL,'Other Anti-bacterial Drugs','22'),
('Vancomycin','Injection','500 mg',NULL,'R',NULL,'Other Anti-bacterial Drugs','22'),
('Amoxicillin','Capsule','250 mg','A','R',NULL,'Penicillins','22'),
('Amoxicillin','Capsule','500 mg','A','R',NULL,'Penicillins','22'),
('Amoxicillin','Suspension','125 mg/5 ml','A','R',NULL,'Penicillins','22'),
('Amoxicillin + Clavulanic Acid','Injection','500 mg + 100 mg','B2','R',NULL,'Penicillins','23'),
('Amoxicillin + Clavulanic Acid','Suspension','250 mg + 62 mg','B1','R',NULL,'Penicillins','23'),
('Amoxicillin + Clavulanic Acid','Suspension','400 mg + 57 mg','B1','R',NULL,'Penicillins','23'),
('Amoxicillin + Clavulanic Acid','Tablet','250 mg + 125 mg','B1','R',NULL,'Penicillins','23'),
('Amoxicillin + Clavulanic Acid','Tablet','500 mg + 125 mg','B1','R',NULL,'Penicillins','23'),
('Ampicillin','Injection','500 mg','B1','R',NULL,'Penicillins','23'),
('Benzathine Benzylpenicillin','Injection','1.2 MU','B2','NR',NULL,'Penicillins','23'),
('Benzathine Benzylpenicillin','Injection','2.4 MU','B2','NR',NULL,'Penicillins','23'),
('Benzyl Penicillin','Injection','1 MU','B1','R',NULL,'Penicillins','23'),
('Benzyl Penicillin','Injection','5 MU','B1','R',NULL,'Penicillins','23'),
('Cloxacillin','Injection','250 mg','B1','R',NULL,'Penicillins','23'),
('Cloxacillin','Injection','500 mg','B1','R',NULL,'Penicillins','23'),
('Flucloxacillin','Capsule','250 mg','B1','R',NULL,'Penicillins','23'),
('Flucloxacillin','Suspension','125 mg/5 ml','B1','R',NULL,'Penicillins','23'),
('Phenoxymethyl Penicillin','Tablet','250 mg','B1','R',NULL,'Penicillins','23'),
('Tetracycline','Capsule','250 mg','B1','R',NULL,'Tetracyclines','23'),
('Fluconazole','Tablet','50 mg','B2','R',NULL,'4.2. Anti-fungal Drugs for systemic use','23'),
('Griseofulvin','Tablet','125 mg','B1','R',NULL,'4.2. Anti-fungal Drugs for systemic use','23'),
('Griseofulvin','Tablet','500 mg','B1','R',NULL,'4.2. Anti-fungal Drugs for systemic use','23'),
('Itraconazole','Tablet','100 mg','D','R',NULL,'4.2. Anti-fungal Drugs for systemic use','23'),
('Miconazole','Oral Gel','20 mg/g','B1','R',NULL,'4.2. Anti-fungal Drugs for systemic use','23'),
('Nystatin','Suspension','100 000 IU/ml','B2','R',NULL,'4.2. Anti-fungal Drugs for systemic use','23'),
('Terbinafine Hydrochloride','Tablet','250 mg','D','R',NULL,'4.2. Anti-fungal Drugs for systemic use','24'),
('Praziquantel','Tablet','600 mg','B1','R',NULL,'Anti-schistosomal','24'),
('Albendazole','Syrup','100 mg/5 ml','A','R',NULL,'Intestinal','24'),
('Albendazole','Tablet','200 mg','A','R',NULL,'Intestinal','24'),
('Albendazole','Tablet','400 mg','A','R',NULL,'Intestinal','24'),
('Mebendazole','Tablet','100 mg','A','R',NULL,'Intestinal','24'),
('Mebendazole','Tablet','500 mg','A','R',NULL,'Intestinal','24'),
('Niclosamide','Tablet','500 mg','B1','R',NULL,'Intestinal','24'),
('Tiabendazole','Suspension','50 mg/ml','B1','R',NULL,'Intestinal','24'),
('Tiabendazole','Tablet','500 mg','B1','R',NULL,'Intestinal','24'),
('Diloxanide Furoate','Suspension','(blank)',NULL,'R',NULL,'Anti-amoebic Drugs','24'),
('Diloxanide Furoate','Tablet','(blank)',NULL,'R',NULL,'Anti-amoebic Drugs','24'),
('Metronidazole','Injection','5 mg/ml','B1','R',NULL,'Anti-amoebic Drugs','24'),
('Metronidazole','Suppository','125 mg','B2','R',NULL,'Anti-amoebic Drugs','24'),
('Metronidazole','Suppository','500 mg','B2','R',NULL,'Anti-amoebic Drugs','24'),
('Metronidazole','Suspension','100 mg/5 ml','A','R',NULL,'Anti-amoebic Drugs','24'),
('Metronidazole','Suspension','200 mg/5 ml','A','R',NULL,'Anti-amoebic Drugs','24'),
('Metronidazole','Tablet','200 mg','A','R',NULL,'Anti-amoebic Drugs','24'),
('Metronidazole','Tablet','400 mg','A','R',NULL,'Anti-amoebic Drugs','24'),
('Paromomycin','Suspension','(blank)',NULL,'R',NULL,'Anti-amoebic Drugs','24'),
('Paromomycin','Tablet','(blank)',NULL,'R',NULL,'Anti-amoebic Drugs','24'),
('Secnidazole','Tablet','500 mg','B2','R',NULL,'Anti-amoebic Drugs','24'),
('Tinidazole','Suspension','(blank)','B2','R',NULL,'Anti-amoebic Drugs','24'),
('Tinidazole','Tablet','500 mg','B2','R',NULL,'Anti-amoebic Drugs','24'),
('Artemether + Lumefantrine','Dispersible Tablet','20 mg + 120 mg','A','R',NULL,'Anti-malarial Drugs','25'),
('Artemether + Lumefantrine','Tablet','20 mg + 120 mg','A','R',NULL,'Anti-malarial Drugs','25'),
('Artesunate','Injection','60 mg (as Anhydrous Aretsunic Acid) + 5% Sodium Bicarbonate Solution for reconstitution','B2','R',NULL,'Anti-malarial Drugs','25'),
('Artesunate','Suppository','200 mg','A','R',NULL,'Anti-malarial Drugs','25'),
('Artesunate','Suppository','50 mg','A','R',NULL,'Anti-malarial Drugs','25'),
('Artesunate + Amodiaquine','Granular Powder','25 mg + 75 mg','A','R',NULL,'Anti-malarial Drugs','25'),
('Artesunate + Amodiaquine','Tablet','100 mg + 270 mg','A','R',NULL,'Anti-malarial Drugs','25'),
('Artesunate + Amodiaquine','Tablet','25 mg + 67.5 mg','A','R',NULL,'Anti-malarial Drugs','25'),
('Artesunate + Amodiaquine','Tablet','25 mg + 75 mg','A','R',NULL,'Anti-malarial Drugs','25'),
('Artesunate + Amodiaquine','Tablet','50 mg + 135 mg','A','R',NULL,'Anti-malarial Drugs','25'),
('Artesunate + Amodiaquine','Tablet','50 mg + 150 mg','A','R',NULL,'Anti-malarial Drugs','25'),
('Arthemether','Injection','40 mg/ml','B2','R',NULL,'Anti-malarial Drugs','25'),
('Arthemether','Injection','80 mg/ml','B2','R',NULL,'Anti-malarial Drugs','25'),
('Dihydroartemisinin + Piperaquine','Tablet','40 mg + 320 mg','A','R',NULL,'Anti-malarial Drugs','25'),
('Quinine','Injection','300 mg/ml in 2 mls','B2','R',NULL,'Anti-malarial Drugs','25'),
('Quinine','Syrup','20 mg/ml','B1','R',NULL,'Anti-malarial Drugs','25'),
('Quinine','Tablet','300 mg','M','R',NULL,'Anti-malarial Drugs','25'),
('Quinine + Clindamycin','Tablet','(blank)',NULL,'R',NULL,'Anti-malarial Drugs','25'),
('Sulfadoxine + Pyrimethamine','Tablet','500 mg + 25 mg','PM','NR',NULL,'Anti-malarial Drugs','26'),
('Acyclovir','Injection','25 mg/ml','C','R',NULL,'4.5. Anti-viral Drugs','26'),
('Acyclovir','Suspension','200 mg/5 ml','B2','R',NULL,'4.5. Anti-viral Drugs','26'),
('Acyclovir','Tablet','200 mg','B2','R',NULL,'4.5. Anti-viral Drugs','26'),
('Carbamazepine','Tablet','100 mg','B2','R',NULL,'5. Anticonvulsants','26'),
('Carbamazepine','Tablet','200 mg','B2','R',NULL,'5. Anticonvulsants','26'),
('Carbamazepine','Tablet (sustained-re- lease)','200 mg','C','R',NULL,'5. Anticonvulsants','26'),
('Carbamazepine','Tablet (sustained-re- lease)','400 mg','C','R',NULL,'5. Anticonvulsants','26'),
('Clonazepam Hydrochloride','Oral Solution','100 microgram/ ml',NULL,'R',NULL,'5. Anticonvulsants','26'),
('Clonazepam Hydrochloride','Tablet','500 microgram',NULL,'R',NULL,'5. Anticonvulsants','26'),
('Diazepam','Injection','5 mg/ml','B1','R',NULL,'5. Anticonvulsants','26'),
('Diazepam','Rectal Tubes','2 mg/ml','A','R',NULL,'5. Anticonvulsants','26'),
('Ethosuximide','Syrup','250 mg/5 ml','D','R',NULL,'5. Anticonvulsants','26'),
('Ethosuximide','Tablet','250 mg','D','R',NULL,'5. Anticonvulsants','26'),
('Lamotrigine','Dispersible Tablet','25 mg',NULL,'R',NULL,'5. Anticonvulsants','26'),
('Lamotrigine','Tablet','25 mg',NULL,'R',NULL,'5. Anticonvulsants','26'),
('Lamotrigine','Tablet','50 mg',NULL,'R',NULL,'5. Anticonvulsants','26'),
('Levetiracetam','Injection','100 mg/ml',NULL,'R',NULL,'5. Anticonvulsants','26'),
('Levetiracetam','Oral Solution','100 mg/ml',NULL,'R',NULL,'5. Anticonvulsants','26'),
('Levetiracetam','Tablet','250 mg',NULL,'R',NULL,'5. Anticonvulsants','26'),
('Levetiracetam','Tablet','750 mg',NULL,'R',NULL,'5. Anticonvulsants','26'),
('Lorazepam','Injection','4 mg/ml','D','R',NULL,'5. Anticonvulsants','26'),
('Magnesium Sulphate','Injection','20%','M','R',NULL,'5. Anticonvulsants','27'),
('Magnesium Sulphate','Injection','25%','M','R',NULL,'5. Anticonvulsants','27'),
('Magnesium Sulphate','Injection','50%','M','R',NULL,'5. Anticonvulsants','27'),
('Midazolam','Injection','5 mg/ml','C','R',NULL,'5. Anticonvulsants','27'),
('Midazolam','Oromucosal Solution','5 mg/ml','C','R',NULL,'5. Anticonvulsants','27'),
('Phenobarbital','Injection','200 mg/ml','B1','R',NULL,'5. Anticonvulsants','27'),
('Phenytoin','Capsule','100 mg','B1','R',NULL,'5. Anticonvulsants','27'),
('Phenytoin','Injection','50 mg/ml','D','R',NULL,'5. Anticonvulsants','27'),
('Phenytoin','Tablet','100 mg','B1','R',NULL,'5. Anticonvulsants','27'),
('Sodium Valproate','Capsule','200 mg','D','R',NULL,'5. Anticonvulsants','27'),
('Sodium Valproate','Capsule','500 mg','D','R',NULL,'5. Anticonvulsants','27'),
('Sodium Valproate','Syrup','200 mg/5 ml','D','R',NULL,'5. Anticonvulsants','27'),
('Sodium Valproate','Tablet','200 mg','D','R',NULL,'5. Anticonvulsants','27'),
('Acetylcysteine','Injection','200 mg/ml','B1','R',NULL,'6.1. Specific antidotes','27'),
('Activated Charcoal','Powder','50 g','A','R',NULL,'6.1. Specific antidotes','27'),
('Adrenaline (Epinephrine)','Injection','1 mg /ml (1:1000)','M','R',NULL,'6.1. Specific antidotes','27'),
('Atropine','Injection','0.6 mg/ml','B2','R',NULL,'6.1. Specific antidotes','27'),
('Benzatropine','Injection','1 mg/ml','C','R',NULL,'6.1. Specific antidotes','27'),
('Cholestyramine','Oral Powder Sachets','4 g',NULL,'R',NULL,'6.1. Specific antidotes','27'),
('Desferrioxamine','Injection','500 mg',NULL,'R',NULL,'6.1. Specific antidotes','27'),
('Diazepam','Injection','10 mg/ml','B1','R',NULL,'6.1. Specific antidotes','27'),
('Ethanol','Solution','10%',NULL,'R',NULL,'6.1. Specific antidotes','27'),
('Flumazenil','Injection','0.2 mg','D','R',NULL,'6.1. Specific antidotes','27'),
('Fomepizole','Injection','5 mg/ml',NULL,'R',NULL,'6.1. Specific antidotes','27'),
('Fresh Frozen Plasma','(blank)','(blank)',NULL,'(blank)',NULL,'6.1. Specific antidotes','28'),
('Hydroxocobalamin','Injection','1 mg/ml','D','R',NULL,'6.1. Specific antidotes','28'),
('N-acetylcysteine','Injection','200 mg/ml','C','R',NULL,'6.1. Specific antidotes','28'),
('Naloxone','Injection','200 microgram/ ml','C','R',NULL,'6.1. Specific antidotes','28'),
('Naloxone','Injection','400 microgram/ ml','C','R',NULL,'6.1. Specific antidotes','28'),
('Omeprazole','Tablet','40 mg','B1','R',NULL,'6.1. Specific antidotes','28'),
('Phytomenadione','Injection','10 mg/ml','M','R',NULL,'6.1. Specific antidotes','28'),
('Phytomenadione','Tablet','10 mg','B2','NR',NULL,'6.1. Specific antidotes','28'),
('Promethazine Hydrochloride','Tablet','25 mg','A','R',NULL,'6.1. Specific antidotes','28'),
('Ranitidine','Injection','25 mg/ml','C','R',NULL,'6.1. Specific antidotes','28'),
('Ranitidine','Tablet','150 mg','B2','R',NULL,'6.1. Specific antidotes','28'),
('Salbutamol','Tablet','4 mg',NULL,'(blank)',NULL,'6.1. Specific antidotes','28'),
('Sodium Thiosulfate','(blank)','(blank)',NULL,'R',NULL,'6.1. Specific antidotes','28'),
('Aspirin','Tablet','300 mg','A','R',NULL,'7. Anti-migrane Drugs','28'),
('Clonidine','Tablet','100 microgram',NULL,'R',NULL,'7. Anti-migrane Drugs','28'),
('Clonidine','Tablet','25 microgram',NULL,'R',NULL,'7. Anti-migrane Drugs','28'),
('Paracetamol','Tablet','500 mg','A','R',NULL,'7. Anti-migrane Drugs','28'),
('Propranolol','Tablet','40 mg','B2','R',NULL,'7. Anti-migrane Drugs','28'),
('Actinomycin D','Injection','10 mg',NULL,'NR',NULL,'8.1 Cytotoxic Drugs','28'),
('Adriamycin Hydrochloride','Injection','10 mg','D','NR',NULL,'8.1 Cytotoxic Drugs','28'),
('Adriamycin Hydrochloride','Injection','50 mg','D','R',NULL,'8.1 Cytotoxic Drugs','28'),
('Bacillus Calmette-Guerin','Injection','12.5 mg','SM','NR',NULL,'8.1 Cytotoxic Drugs','28'),
('Bacillus Calmette-Guerin','Injection','81 mg','SM','NR',NULL,'8.1 Cytotoxic Drugs','29'),
('Bicalutamide','Tablet','100 mg','D','NR',NULL,'8.1 Cytotoxic Drugs','29'),
('Bicalutamide','Tablet','50 mg','D','NR',NULL,'8.1 Cytotoxic Drugs','29'),
('Carboplatin','Injection','10 mg/ml',NULL,'NR',NULL,'8.1 Cytotoxic Drugs','29'),
('Cisplatin','Injection','50 mg','D','NR',NULL,'8.1 Cytotoxic Drugs','29'),
('Cyclophosphamide','Injection','200 mg','D','NR',NULL,'8.1 Cytotoxic Drugs','29'),
('Cyclophosphamide','Injection','500 mg','D','R',NULL,'8.1 Cytotoxic Drugs','29'),
('Cyclophosphamide','Tablet','50 mg','D','NR',NULL,'8.1 Cytotoxic Drugs','29'),
('Doxorubucin','Injection','10 mg',NULL,'NR',NULL,'8.1 Cytotoxic Drugs','29'),
('Doxorubucin','Injection','2 mg/ml',NULL,'NR',NULL,'8.1 Cytotoxic Drugs','29'),
('Etoposide','Capsule','100 mg','D','NR',NULL,'8.1 Cytotoxic Drugs','29'),
('Etoposide','Injection','20 mg/ml','D','NR',NULL,'8.1 Cytotoxic Drugs','29'),
('Flutamide','Tablet','250 mg','D','NR',NULL,'8.1 Cytotoxic Drugs','29'),
('Goserelin','Injection','10.8 mg','D','NR',NULL,'8.1 Cytotoxic Drugs','29'),
('Goserelin','Injection','3.6 mg','D','NR',NULL,'8.1 Cytotoxic Drugs','29'),
('Hydroxycarbamide','Capsule','500 mg','SM','NR',NULL,'8.1 Cytotoxic Drugs','29'),
('Leuprolide Acetate','Injection','3.75 mg/ml','D','NR',NULL,'8.1 Cytotoxic Drugs','29'),
('Methotrexate','Injection','2.5 mg/ml','D','R',NULL,'8.1 Cytotoxic Drugs','29'),
('Methotrexate','Injection','25 mg/ml','D','R',NULL,'8.1 Cytotoxic Drugs','29'),
('Methotrexate','Tablet','10 mg','D','R',NULL,'8.1 Cytotoxic Drugs','29'),
('Methotrexate','Tablet','2.5 mg','D','R',NULL,'8.1 Cytotoxic Drugs','29'),
('Stilboestrol','Tablet','1 mg','D','NR',NULL,'8.1 Cytotoxic Drugs','29'),
('Stilboestrol','Tablet','2 mg','D','NR',NULL,'8.1 Cytotoxic Drugs','29'),
('Stilboestrol','Tablet','5 mg','D','NR',NULL,'8.1 Cytotoxic Drugs','29'),
('Thiotepa','Injection','15 mg','SM','NR',NULL,'8.1 Cytotoxic Drugs','29'),
('Vinblastine','Injection','1 mg/ml','D','NR',NULL,'8.1 Cytotoxic Drugs','29'),
('Vincristine','Injection','1 mg','D','NR',NULL,'8.1 Cytotoxic Drugs','29'),
('Vincristine','Injection','2 mg','D','NR',NULL,'8.1 Cytotoxic Drugs','29'),
('Vincristine','Injection','5 mg','D','NR',NULL,'8.1 Cytotoxic Drugs','29'),
('Prednisolone','Tablet','5 mg','B2','R',NULL,'8.2. Hormones and Anit-hormones','30'),
('Benzatropine','Tablet','2 mg','C','R',NULL,'9. Anti-parkinsonism Drugs','30'),
('Biperiden','Injection','5 mg/ml','C','NR',NULL,'9. Anti-parkinsonism Drugs','30'),
('Biperiden','Tablet','2 mg','C','NR',NULL,'9. Anti-parkinsonism Drugs','30'),
('Trihexyphenidyl','Tablet','2 mg','C','R',NULL,'9. Anti-parkinsonism Drugs','30'),
('Trihexyphenidyl','Tablet','5 mg','C','R',NULL,'9. Anti-parkinsonism Drugs','30'),
('Cryoprecipitate','Injection','(blank)','B2','NR',NULL,'10. Blood products and Blood substitutes','30'),
('Fresh Frozen Plasma','Injection','(blank)','B2','NR',NULL,'10. Blood products and Blood substitutes','30'),
('Packed Red Cells','Injection','(blank)','B2','NR',NULL,'10. Blood products and Blood substitutes','30'),
('Platelet Concentrate','Injection','(blank)','B2','NR',NULL,'10. Blood products and Blood substitutes','30'),
('Purified Factor IX','Injection','(blank)',NULL,'R',NULL,'10. Blood products and Blood substitutes','30'),
('Purified Factor VIII','Injection','(blank)',NULL,'R',NULL,'10. Blood products and Blood substitutes','30'),
('Recombinant Factor IX','Injection','(blank)',NULL,'R',NULL,'10. Blood products and Blood substitutes','30'),
('Recombinant Factor VIII','Injection','(blank)',NULL,'R',NULL,'10. Blood products and Blood substitutes','30'),
('Salt-poor Human Albumin','Solution','(blank)',NULL,'R',NULL,'10. Blood products and Blood substitutes','30'),
('Whole blood','(blank)','(blank)',NULL,'(blank)',NULL,'10. Blood products and Blood substitutes','30'),
('Aspirin','Chewable Tablet','300 mg','C','R',NULL,'11.1 Anti-anginal Drugs','30'),
('Glyceryl Trinitrate','Tablet','500 microgram','C','R',NULL,'11.1 Anti-anginal Drugs','30'),
('Isosorbide Dinitrate','Tablet','10 mg','C','R',NULL,'11.1 Anti-anginal Drugs','30'),
('Isosorbide Dinitrate','Tablet','5 mg','C','R',NULL,'11.1 Anti-anginal Drugs','30'),
('Nifedipine','Tablet','10 mg (Slow release)','B2','R',NULL,'11.1 Anti-anginal Drugs','30'),
('Nifedipine','Tablet','20 mg (Slow release)','B2','R',NULL,'11.1 Anti-anginal Drugs','31'),
('Nifedipine','Tablet','30 mg (GITS)','B2','R',NULL,'11.1 Anti-anginal Drugs','31'),
('Propranolol','Tablet','10 mg','B2','R',NULL,'11.1 Anti-anginal Drugs','31'),
('Propranolol','Tablet','40 mg','B2','R',NULL,'11.1 Anti-anginal Drugs','31'),
('Propranolol','Tablet','80 mg','B2','R',NULL,'11.1 Anti-anginal Drugs','31'),
('Atenolol','Tablet','25 mg','B2','R',NULL,'11.2. Anti-dysrythmic','31'),
('Atenolol','Tablet','50 mg','B2','R',NULL,'11.2. Anti-dysrythmic','31'),
('Bisoprolol','Tablet','5 mg','B2','R',NULL,'11.2. Anti-dysrythmic','31'),
('Digoxin','Elixir','50 microgram/ ml','C','R',NULL,'11.2. Anti-dysrythmic','31'),
('Digoxin','Tablet','125 microgram','C','R',NULL,'11.2. Anti-dysrythmic','31'),
('Digoxin','Tablet','250 microgram','C','R',NULL,'11.2. Anti-dysrythmic','31'),
('Metoprolol Tartrate','Tablet','100 mg',NULL,'R',NULL,'11.2. Anti-dysrythmic','31'),
('Metoprolol Tartrate','Tablet','50 mg',NULL,'R',NULL,'11.2. Anti-dysrythmic','31'),
('Propranolol','Tablet','10 mg','B2','R',NULL,'11.2. Anti-dysrythmic','31'),
('Propranolol','Tablet','40 mg','B2','R',NULL,'11.2. Anti-dysrythmic','31'),
('Propranolol','Tablet','80 mg','B2','R',NULL,'11.2. Anti-dysrythmic','31'),
('Verapamil','Tablet','(blank)',NULL,'R',NULL,'11.2. Anti-dysrythmic','31'),
('Amlodipine','Tablet','10 mg','B2','R',NULL,'11.3. Anti-hypertensive Drugs','31'),
('Amlodipine','Tablet','5 mg','B2','R',NULL,'11.3. Anti-hypertensive Drugs','31'),
('Atenolol','Injection','500 microgram/ ml','D','R',NULL,'11.3. Anti-hypertensive Drugs','31'),
('Atenolol','Tablet','100 mg','B2','R',NULL,'11.3. Anti-hypertensive Drugs','31'),
('Atenolol','Tablet','25 mg','B2','R',NULL,'11.3. Anti-hypertensive Drugs','31'),
('Atenolol','Tablet','50 mg','B2','R',NULL,'11.3. Anti-hypertensive Drugs','31'),
('Bendroflumethiazide','Tablet','2.5 mg','B2','R',NULL,'11.3. Anti-hypertensive Drugs','32'),
('Bendroflumethiazide','Tablet','5 mg','B1','R',NULL,'11.3. Anti-hypertensive Drugs','32'),
('Bisoprolol','Tablet','10 mg','B2','R',NULL,'11.3. Anti-hypertensive Drugs','32'),
('Bisoprolol','Tablet','5 mg','B2','R',NULL,'11.3. Anti-hypertensive Drugs','32'),
('Candesartan','Tablet','16 mg','D','NR',NULL,'11.3. Anti-hypertensive Drugs','32'),
('Candesartan','Tablet','8 mg','D','NR',NULL,'11.3. Anti-hypertensive Drugs','32'),
('Cervedilol','Tablet','12.5 mg',NULL,'R',NULL,'11.3. Anti-hypertensive Drugs','32'),
('Cervedilol','Tablet','3.125 mg',NULL,'R',NULL,'11.3. Anti-hypertensive Drugs','32'),
('Dobutamide','Injection','12.5 mg/ml','D','NR',NULL,'11.3. Anti-hypertensive Drugs','32'),
('Enalapril','Tablet','10 mg','B2','R',NULL,'11.3. Anti-hypertensive Drugs','32'),
('Enalapril','Tablet','2.5 mg','B2','R',NULL,'11.3. Anti-hypertensive Drugs','32'),
('Hydralazine','Injection','20 mg','C','R',NULL,'11.3. Anti-hypertensive Drugs','32'),
('Hydralazine','Tablet','25 mg','B2','R',NULL,'11.3. Anti-hypertensive Drugs','32'),
('Hydrochlorothiazide','Tablet','12.5 mg',NULL,'R',NULL,'11.3. Anti-hypertensive Drugs','32'),
('Hydrochlorothiazide','Tablet','25 mg','B2','R',NULL,'11.3. Anti-hypertensive Drugs','32'),
('Labetalol','Injection','5 mg/ml','D','R',NULL,'11.3. Anti-hypertensive Drugs','32'),
('Labetalol','Tablet','200 mg','B2','R',NULL,'11.3. Anti-hypertensive Drugs','32'),
('Labetalol','Tablet','50 mg','B2','R',NULL,'11.3. Anti-hypertensive Drugs','32'),
('Lisinopril','Tablet','10 mg','B2','R',NULL,'11.3. Anti-hypertensive Drugs','32'),
('Lisinopril','Tablet','2.5 mg','B2','R',NULL,'11.3. Anti-hypertensive Drugs','32'),
('Lisinopril','Tablet','5 mg','B2','R',NULL,'11.3. Anti-hypertensive Drugs','32'),
('Losartan','Tablet','100 mg','C','R',NULL,'11.3. Anti-hypertensive Drugs','32'),
('Losartan','Tablet','25 mg','C','R',NULL,'11.3. Anti-hypertensive Drugs','32'),
('Losartan','Tablet','50 mg','C','R',NULL,'11.3. Anti-hypertensive Drugs','32'),
('Methyldopa','Tablet','250 mg','M','R',NULL,'11.3. Anti-hypertensive Drugs','32'),
('Metoprolol Tartrate','Tablet','50 mg',NULL,'R',NULL,'11.3. Anti-hypertensive Drugs','32'),
('Nifedipine','Tablet','10 mg','C','R',NULL,'11.3. Anti-hypertensive Drugs','32'),
('Nifedipine','Tablet','10 mg (Slow release)','M','R',NULL,'11.3. Anti-hypertensive Drugs','32'),
('Nifedipine','Tablet','20 mg (Slow release)','M','R',NULL,'11.3. Anti-hypertensive Drugs','33'),
('Nifedipine','Tablet','30 mg (GITS)','M','R',NULL,'11.3. Anti-hypertensive Drugs','33'),
('Nifedipine','Tablet','5 mg','D','R',NULL,'11.3. Anti-hypertensive Drugs','33'),
('Prazosin','Tablet','500 microgram','D','R',NULL,'11.3. Anti-hypertensive Drugs','33'),
('Propranolol','Injection','1 mg/ml','D','R',NULL,'11.3. Anti-hypertensive Drugs','33'),
('Propranolol','Tablet','10 mg','B2','R',NULL,'11.3. Anti-hypertensive Drugs','33'),
('Propranolol','Tablet','40 mg','B2','R',NULL,'11.3. Anti-hypertensive Drugs','33'),
('Propranolol','Tablet','80 mg','B2','R',NULL,'11.3. Anti-hypertensive Drugs','33'),
('Ramipril','Tablet','2.5 mg','C','R',NULL,'11.3. Anti-hypertensive Drugs','33'),
('Spironolactone','Tablet','25 mg','C','R',NULL,'11.3. Anti-hypertensive Drugs','33'),
('Spironolactone','Tablet','50 mg','C','R',NULL,'11.3. Anti-hypertensive Drugs','33'),
('Valsartan','Tablet','160 mg',NULL,'R',NULL,'11.3. Anti-hypertensive Drugs','33'),
('Valsartan','Tablet','40 mg',NULL,'R',NULL,'11.3. Anti-hypertensive Drugs','33'),
('Digoxin','Elixir','50 microgram/ ml','C','R',NULL,'11.4. Cardiac Glycosides','33'),
('Digoxin','Tablet','125 microgram','C','R',NULL,'11.4. Cardiac Glycosides','33'),
('Digoxin','Tablet','250 microgram','C','R',NULL,'11.4. Cardiac Glycosides','33'),
('Hydrocortisone','Injection','100 mg','M','R',NULL,'11.5. Drugs used in shock','33'),
('Polygeline','Infusion','3.5%',NULL,'R',NULL,'11.5. Drugs used in shock','33'),
('Insulin Aspart (Fast acting)','Injection','100 units/ml','C','NR',NULL,'11.6. Insulins and other antidiabetic drugs','33'),
('Atorvastatin','Tablet','10 mg','C','R',NULL,'11.7. Lipid-regulating Drugs','33'),
('Atorvastatin','Tablet','20 mg','C','R',NULL,'11.7. Lipid-regulating Drugs','33'),
('Rosuvastatin','Tablet','10 mg','C','R',NULL,'11.7. Lipid-regulating Drugs','34'),
('Rosuvastatin','Tablet','5 mg','C','R',NULL,'11.7. Lipid-regulating Drugs','34'),
('Simvastatin','Tablet','10 mg','C','R',NULL,'11.7. Lipid-regulating Drugs','34'),
('Simvastatin','Tablet','20 mg','C','R',NULL,'11.7. Lipid-regulating Drugs','34'),
('Simvastatin','Tablet','30 mg','C','R',NULL,'11.7. Lipid-regulating Drugs','34'),
('Simvastatin','Tablet','40 mg','C','R',NULL,'11.7. Lipid-regulating Drugs','34'),
('Dobutamine','Solution for Infusion','5 mg/ml',NULL,'R',NULL,'11.8. Others','34'),
('Acyclovir','Cream','5%','C','R',NULL,'12.1. Anti-infective Drugs','34'),
('Adapalene','Cream','0.1%',NULL,'R',NULL,'12.1. Anti-infective Drugs','34'),
('Adapalene','Gel','0.1%',NULL,'R',NULL,'12.1. Anti-infective Drugs','34'),
('Cetrimide','Solution','15%','M','NR',NULL,'12.1. Anti-infective Drugs','34'),
('Cetrimide + Chlorhexidine Gluconate','Solution','0.15% + 0.015%','A','R',NULL,'12.1. Anti-infective Drugs','34'),
('Cetrimide + Chlorhexidine Gluconate','Solution','15% + 1.5%','A','R',NULL,'12.1. Anti-infective Drugs','34'),
('Chlorhexidine','Gel','7.1% (digluconate) delivering 4% chlorhexidine','A','R',NULL,'12.1. Anti-infective Drugs','34'),
('Chlorhexidine','Solution','7.1% (digluconate) delivering 4% chlorhexidine','A','R',NULL,'12.1. Anti-infective Drugs','34'),
('Fusidic Acid','Cream','2%',NULL,'R',NULL,'12.1. Anti-infective Drugs','34'),
('Mupirocin','Ointment','2%',NULL,'R',NULL,'12.1. Anti-infective Drugs','34'),
('Povidone Iodine','Solution','10%',NULL,'R',NULL,'12.1. Anti-infective Drugs','34'),
('Silver Sulphadiazine','Cream','1%','B1','R',NULL,'12.1. Anti-infective Drugs','34'),
('Betamethasone Diproprionate','Cream','0.05%','C','R',NULL,'12.2. Anti-inflammatory and Anti-pruritic Drugs','35'),
('Betamethasone Diproprionate','Cream','0.1%','C','R',NULL,'12.2. Anti-inflammatory and Anti-pruritic Drugs','35'),
('Calamine','Cream','15%','A','R',NULL,'12.2. Anti-inflammatory and Anti-pruritic Drugs','35'),
('Calamine','Lotion','15%','A','R',NULL,'12.2. Anti-inflammatory and Anti-pruritic Drugs','35'),
('Clobetasol Propionate','Cream','0.05%',NULL,'R',NULL,'12.2. Anti-inflammatory and Anti-pruritic Drugs','35'),
('Hydrocortisone','Cream','0.5%','B1','R',NULL,'12.2. Anti-inflammatory and Anti-pruritic Drugs','35'),
('Hydrocortisone','Cream','1%','B1','R',NULL,'12.2. Anti-inflammatory and Anti-pruritic Drugs','35'),
('Hydrocortisone','Cream','2.5%','D','R',NULL,'12.2. Anti-inflammatory and Anti-pruritic Drugs','35'),
('Mometasone','Cream','0.1%',NULL,'R',NULL,'12.2. Anti-inflammatory and Anti-pruritic Drugs','35'),
('Zinc Oxide','Cream','(blank)',NULL,'R',NULL,'12.2. Anti-inflammatory and Anti-pruritic Drugs','35'),
('Benzoic Acid + Salicylic Acid','Ointment','6% + 3%','A','R',NULL,'12.3. Anti-fungal Drugs','35'),
('Ciclopirox Olamine','Cream','1%','B1','R',NULL,'12.3. Anti-fungal Drugs','35'),
('Clotrimazole','Cream','1%','A','R',NULL,'12.3. Anti-fungal Drugs','35'),
('Clotrimazole','Cream','2%','A','R',NULL,'12.3. Anti-fungal Drugs','35'),
('Clotrimazole','Pessary','100 mg','M','R',NULL,'12.3. Anti-fungal Drugs','35'),
('Clotrimazole','Powder','1%','A','R',NULL,'12.3. Anti-fungal Drugs','35'),
('Clotrimazole','Topical Solution','1%','A','R',NULL,'12.3. Anti-fungal Drugs','35'),
('Clotrimazole + Hydrocortisone','Cream','1% + 1%','C','R',NULL,'12.3. Anti-fungal Drugs','35'),
('Clotrimazole + Hydrocortisone','Cream','2% + 1%','C','NR',NULL,'12.3. Anti-fungal Drugs','35'),
('Econazole','Cream','(blank)',NULL,'R',NULL,'12.3. Anti-fungal Drugs','35'),
('Ketoconazole','Shampoo','(blank)','C','R',NULL,'12.3. Anti-fungal Drugs','35'),
('Miconazole','Cream','2%','B2','R',NULL,'12.3. Anti-fungal Drugs','35'),
('Miconazole','Oral Gel','24 mg/ml','B2','R',NULL,'12.3. Anti-fungal Drugs','35'),
('Miconazole','Powder','2%','B2','R',NULL,'12.3. Anti-fungal Drugs','36'),
('Miconazole','Tincture','(blank)','B2','R',NULL,'12.3. Anti-fungal Drugs','36'),
('Miconazole','Vaginal Tablet','200 mg','B2','R',NULL,'12.3. Anti-fungal Drugs','36'),
('Miconazole + Hydrocortisone','Cream','2% + 1%',NULL,'NR',NULL,'12.3. Anti-fungal Drugs','36'),
('Nystatin','Cream','(blank)','M','R',NULL,'12.3. Anti-fungal Drugs','36'),
('Selenium Sulphide','Shampoo','2.5%','C','R',NULL,'12.3. Anti-fungal Drugs','36'),
('Salicylic Acid','Ointment','0.02','B1','R',NULL,'12.4. Astringent Agents','36'),
('Paraffin','Cream','(blank)','A','R',NULL,'12.5. Emollients and Vehicles','36'),
('Benzyl Benzoate','Lotion','0.25','A','R',NULL,'12.6. Scabicides and Pediculocides','36'),
('Malathoin','Liquid','0.5%',NULL,'R',NULL,'12.6. Scabicides and Pediculocides','36'),
('Permethrin','Lotion','1%',NULL,'R',NULL,'12.6. Scabicides and Pediculocides','36'),
('Adapalene','Cream','0.1%',NULL,'R',NULL,'12.7 Others','36'),
('Adapalene','Gel','0.1%',NULL,'R',NULL,'12.7 Others','36'),
('Benzoyl Peroxide','Solution','0.05','C','R',NULL,'12.7 Others','36'),
('Clindamycin','Solution','1%','C','R',NULL,'12.7 Others','36'),
('Copper Sulphate','Stone','(blank)',NULL,'R',NULL,'12.7 Others','36'),
('E45','Cream','(blank)',NULL,'R',NULL,'12.7 Others','36'),
('Imiquimod','Cream','0.05',NULL,'R',NULL,'12.7 Others','36'),
('Oilatum','Soap','(blank)',NULL,'NR',NULL,'12.7 Others','36'),
('Podophyllin','Tincture of benzoin','10-25%',NULL,'R',NULL,'12.7 Others','36'),
('Podophylotoxin','(blank)','0.5%',NULL,'R',NULL,'12.7 Others','36'),
('Shea Butter','Cream','(blank)',NULL,'NR',NULL,'12.7 Others','36'),
('Tretinoin','Gel','0.01%',NULL,'R',NULL,'12.7 Others','37'),
('Trichloroacetic Acid','(blank)','80-90%',NULL,'R',NULL,'12.7 Others','37'),
('Fluorescein','Solution','2%','C','NR',NULL,'13.1. Ophthalmic Drugs','37'),
('Fluorescein','Strips','(blank)','C','NR',NULL,'13.1. Ophthalmic Drugs','37'),
('Tropicamide','Eye Drops','1%','C','NR',NULL,'13.1. Ophthalmic Drugs','37'),
('Chlorhexidine','Cream','1%','A','R',NULL,'14. Disinfectants','37'),
('Chlorhexidine','Solution','0.025','A','R',NULL,'14. Disinfectants','37'),
('Chlorhexidine','Solution','0.04','A','NR',NULL,'14. Disinfectants','37'),
('Povidone Iodine','Solution','0.1','B1','R',NULL,'14. Disinfectants','37'),
('Bendroflumethiazide','Tablet','2.5 mg','B1','R',NULL,'15. Diuretics','37'),
('Bendroflumethiazide','Tablet','5 mg','B1','R',NULL,'15. Diuretics','37'),
('Furosemide','Injection','10 mg/ml','B2','R',NULL,'15. Diuretics','37'),
('Furosemide','Tablet','40 mg','B1','R',NULL,'15. Diuretics','37'),
('Hypertonic Saline','Injection','0.03',NULL,'R',NULL,'15. Diuretics','37'),
('Mannitol','Injection','0.2','C','R',NULL,'15. Diuretics','37'),
('Metolazone','Tablet','5 mg','D','R',NULL,'15. Diuretics','37'),
('Spironolactone','Tablet','25 mg','C','R',NULL,'15. Diuretics','37'),
('Spironolactone','Tablet','50 mg','C','R',NULL,'15. Diuretics','37'),
('Adrenaline (Epinephrine)','Injection','1 mg /ml (1:1000)','M','R',NULL,'16.1. Anti-asthmatic Drugs','37'),
('Aminophylline','Injection','250 mg/10 ml','B2','R',NULL,'16.1. Anti-asthmatic Drugs','37'),
('Beclometasone Dipropionate','Inhaler','100 microgram/ metered dose (200 doses)','B2','R',NULL,'16.1. Anti-asthmatic Drugs','38'),
('Budesonide','metered dose inhaler','100 microgram','D','R',NULL,'16.1. Anti-asthmatic Drugs','38'),
('Budesonide','metered dose inhaler','200 microgram','D','R',NULL,'16.1. Anti-asthmatic Drugs','38'),
('Budesonide + Formoterol','Inhaler','160 microgram + 4.5 microgram','D','R',NULL,'16.1. Anti-asthmatic Drugs','38'),
('Budesonide + Formoterol','Inhaler','80 microgram + 4.5 microgram','D','R',NULL,'16.1. Anti-asthmatic Drugs','38'),
('Fluticasone','Inhaler','125 microgram','D','R',NULL,'16.1. Anti-asthmatic Drugs','38'),
('Fluticasone','Inhaler','250 microgram','D','R',NULL,'16.1. Anti-asthmatic Drugs','38'),
('Fluticasone + Salmeterol','Inhaler','250 microgram + 50 microgram','D','R',NULL,'16.1. Anti-asthmatic Drugs','38'),
('Hydrocortisone','Injection','100 mg','M','R',NULL,'16.1. Anti-asthmatic Drugs','38'),
('Ipratropium Bromide','Nebuliser','(blank)',NULL,'R',NULL,'16.1. Anti-asthmatic Drugs','38'),
('Montelukast','Chewable Tablet','4 mg',NULL,'R',NULL,'16.1. Anti-asthmatic Drugs','38'),
('Montelukast','Chewable Tablet','5 mg',NULL,'R',NULL,'16.1. Anti-asthmatic Drugs','38'),
('Montelukast','Granule Sachets','4 mg',NULL,'R',NULL,'16.1. Anti-asthmatic Drugs','38'),
('Montelukast','Granule Sachets','5 mg',NULL,'R',NULL,'16.1. Anti-asthmatic Drugs','38'),
('Montelukast','Tablet','10 mg',NULL,'R',NULL,'16.1. Anti-asthmatic Drugs','38'),
('Prednisolone','Tablet','5 mg','B2','R',NULL,'16.1. Anti-asthmatic Drugs','38'),
('Salbutamol','Nebuliser','2.5 mg nebules','B1','R',NULL,'16.1. Anti-asthmatic Drugs','39'),
('Salbutamol','Nebuliser','5 mg nebules','B1','R',NULL,'16.1. Anti-asthmatic Drugs','39'),
('Salbutamol','Pressurized metered dose Inhaler','100 microgram/ metered dose (200 doses)','A','R',NULL,'16.1. Anti-asthmatic Drugs','39'),
('Salbutamol','Syrup','2 mg/5 ml','B1','R',NULL,'16.1. Anti-asthmatic Drugs','39'),
('Salbutamol','Tablet','2 mg','B1','R',NULL,'16.1. Anti-asthmatic Drugs','39'),
('Salbutamol','Tablet','4 mg','B1','R',NULL,'16.1. Anti-asthmatic Drugs','39'),
('Theophylline','Tablet (slow release)','200 mg','B2','R',NULL,'16.1. Anti-asthmatic Drugs','39'),
('Tiotropium Bromide','Inhaler (dry powder)','(blank)',NULL,'R',NULL,'16.1. Anti-asthmatic Drugs','39'),
('Acetylcysteine','Syrup','(blank)','B1','R',NULL,'16.2. Antitussives','39'),
('Carbocysteine','Capsule','375 mg','B1','R',NULL,'16.2. Antitussives','39'),
('Carbocysteine','Syrup','125 mg/5 ml','B1','R',NULL,'16.2. Antitussives','39'),
('Carbocysteine','Syrup','250 mg/5 ml','B1','R',NULL,'16.2. Antitussives','39'),
('Codeine containing cough preparations','Syrup','(blank)',NULL,'R',NULL,'16.2. Antitussives','39'),
('Dextromethorphan containing cough preparations','Syrup','(blank)',NULL,'R',NULL,'16.2. Antitussives','39'),
('Guaifenesin containing experorant','Syrup','(blank)',NULL,'R',NULL,'16.2. Antitussives','39'),
('Simple Linctus','Paediatric Formulation','(blank)','A','R',NULL,'16.2. Antitussives','39'),
('Simple Linctus','Syrup','(blank)','A','R',NULL,'16.2. Antitussives','39'),
('Oxygen','Inhalation','(blank)','M','NR',NULL,'16.3. Others','39'),
('Darbepoietin alfa','Injection','100 microgram/ ml',NULL,'(blank)',NULL,'17.1. Anti-anaemia Drugs','40'),
('Darbepoietin alfa','Injection','25 microgram/ ml',NULL,'(blank)',NULL,'17.1. Anti-anaemia Drugs','40'),
('Darbepoietin alfa','Injection','500 microgram/ ml',NULL,'(blank)',NULL,'17.1. Anti-anaemia Drugs','40'),
('Epoietin beta','Injection','10 000 units/ ml',NULL,'(blank)',NULL,'17.1. Anti-anaemia Drugs','40'),
('Epoietin beta','Injection','2000 units/ ml',NULL,'(blank)',NULL,'17.1. Anti-anaemia Drugs','40'),
('Ferric Sodium Gluconate complex','Injection','(blank)',NULL,'(blank)',NULL,'17.1. Anti-anaemia Drugs','40'),
('Ferrous Fumarate','Tablet','65 mg elemental iron','A','R',NULL,'17.1. Anti-anaemia Drugs','40'),
('Ferrous Gluconate','(blank)','(blank)',NULL,'(blank)',NULL,'17.1. Anti-anaemia Drugs','40'),
('Ferrous Sulphate','Syrup','60 mg/5 ml','A','(blank)',NULL,'17.1. Anti-anaemia Drugs','40'),
('Ferrous Sulphate','Tablet','65 mg elemental iron','A','(blank)',NULL,'17.1. Anti-anaemia Drugs','40'),
('Folic Acid','Tablet','5 mg','A','R',NULL,'17.1. Anti-anaemia Drugs','40'),
('Hydroxocobalamin','Injection','1 mg/ml','D','R',NULL,'17.1. Anti-anaemia Drugs','40'),
('Iron (III) Hydroxide Polymaltose Complex','Capsule','100 mg elemental iron',NULL,'R',NULL,'17.1. Anti-anaemia Drugs','40'),
('Iron (III) Hydroxide Polymaltose Complex','Suspension','100 mg elemental iron',NULL,'R',NULL,'17.1. Anti-anaemia Drugs','40'),
('Iron Dextran','Injection','100 mg/2 ml','C','R',NULL,'17.1. Anti-anaemia Drugs','40'),
('Iron Sucrose','Injection','20 mg/ml','SM','R',NULL,'17.1. Anti-anaemia Drugs','40'),
('Methoxy polyethylene glycol epoietin beta (pegylated form of Epo)','Injection','100 microgram/ ml',NULL,'(blank)',NULL,'17.1. Anti-anaemia Drugs','41'),
('Methoxy polyethylene glycol epoietin beta (pegylated form of Epo)','Injection','500 microgram/ ml',NULL,'(blank)',NULL,'17.1. Anti-anaemia Drugs','41'),
('Aspirin','Dispersible Tablet','75 mg','B2','R',NULL,'17.2. Anti-coagulants and Antagonists','41'),
('Clopidogrel','Tablet','75 mg',NULL,'R',NULL,'17.2. Anti-coagulants and Antagonists','41'),
('Dalteparin','Injection','10 000 units/ ml','D','R',NULL,'17.2. Anti-coagulants and Antagonists','41'),
('Dalteparin','Injection','25 000 units/ ml','D','R',NULL,'17.2. Anti-coagulants and Antagonists','41'),
('Dalteparin','Injection','2500 units/ ml','D','R',NULL,'17.2. Anti-coagulants and Antagonists','41'),
('Desmopressin','Nasal Spray','150 microgram/ dose',NULL,'R',NULL,'17.2. Anti-coagulants and Antagonists','41'),
('Enoxaparin','Injection','100 mg/ml','C','R',NULL,'17.2. Anti-coagulants and Antagonists','41'),
('Heparin','Injection','1000 units/ ml','D','R',NULL,'17.2. Anti-coagulants and Antagonists','41'),
('Heparin','Injection','25 000 units/ ml','D','R',NULL,'17.2. Anti-coagulants and Antagonists','41'),
('Heparin','Injection','5000 units/ ml','D','R',NULL,'17.2. Anti-coagulants and Antagonists','41'),
('Phytomenadione','Injection','1 mg/ml','M','R',NULL,'17.2. Anti-coagulants and Antagonists','41'),
('Phytomenadione','Injection','10 mg/ml','M','R',NULL,'17.2. Anti-coagulants and Antagonists','41'),
('Phytomenadione','Tablet','10 mg','B2','NR',NULL,'17.2. Anti-coagulants and Antagonists','41'),
('Tranexamic Acid','Capsule','250 mg','C','R',NULL,'17.2. Anti-coagulants and Antagonists','41'),
('Tranexamic Acid','Injection','50 microgram/ ml','D','R',NULL,'17.2. Anti-coagulants and Antagonists','41'),
('Tranexamic Acid','Tablet','500 mg','C','R',NULL,'17.2. Anti-coagulants and Antagonists','41'),
('Warfarin','Tablet','1 mg','D','R',NULL,'17.2. Anti-coagulants and Antagonists','41'),
('Warfarin','Tablet','3 mg','D','R',NULL,'17.2. Anti-coagulants and Antagonists','42'),
('Warfarin','Tablet','5 mg','D','R',NULL,'17.2. Anti-coagulants and Antagonists','42'),
('Aluminium Hydroxide','Tablet','500 mg','A','R',NULL,'18.1 Antacids and other Anti-ulcer Drugs','42'),
('Antacid containing (Aluminium Hydroxide, Magnesium Hydroxide, Simethicone, Calcium alginates)','Mixture','(blank)',NULL,'R',NULL,'18.1 Antacids and other Anti-ulcer Drugs','42'),
('Esomeprazole','Capsule','20 mg','C','R',NULL,'18.1 Antacids and other Anti-ulcer Drugs','42'),
('Esomeprazole','Capsule','40 mg','C','R',NULL,'18.1 Antacids and other Anti-ulcer Drugs','42'),
('Esomeprazole','Injection','40 mg','C','NR',NULL,'18.1 Antacids and other Anti-ulcer Drugs','42'),
('Magnesium Trisilicate','Mixture','(blank)','A','R',NULL,'18.1 Antacids and other Anti-ulcer Drugs','42'),
('Magnesium Trisilicate','Tablet','500 mg','A','R',NULL,'18.1 Antacids and other Anti-ulcer Drugs','42'),
('Omeprazole','Tablet','20 mg','B1','R',NULL,'18.1 Antacids and other Anti-ulcer Drugs','42'),
('Pantoprazole','Tablet','40 mg',NULL,'R',NULL,'18.1 Antacids and other Anti-ulcer Drugs','42'),
('Rabeprazole','Capsule','10 mg','C','NR',NULL,'18.1 Antacids and other Anti-ulcer Drugs','42'),
('Rabeprazole','Capsule','20 mg','C','R',NULL,'18.1 Antacids and other Anti-ulcer Drugs','42'),
('Cinnarizine','Injection','15 mg',NULL,'R',NULL,'18.2. Anti-emetics','42'),
('Cyclizine','Injection','50 mg/ml',NULL,'R',NULL,'18.2. Anti-emetics','42'),
('Cyclizine','Tablet','50 mg',NULL,'R',NULL,'18.2. Anti-emetics','42'),
('Dexamethasone','Tablet','1 mg','D','R',NULL,'18.2. Anti-emetics','42'),
('Dexamethasone','Tablet','500 microgram','D','R',NULL,'18.2. Anti-emetics','42'),
('Domperidone','Oral Solution','1 mg/ml','D','R',NULL,'18.2. Anti-emetics','42'),
('Domperidone','Tablet','10 mg','D','R',NULL,'18.2. Anti-emetics','42'),
('Granisetron','Injection','1 mg/ml','D','R',NULL,'18.2. Anti-emetics','42'),
('Granisetron','Tablet','1 mg','D','R',NULL,'18.2. Anti-emetics','42'),
('Lorazepam','Injection','4 mg/ml','D','R',NULL,'18.2. Anti-emetics','42'),
('Lorazepam','Tablet','1 mg','B2','R',NULL,'18.2. Anti-emetics','43'),
('Lorazepam','Tablet','2 mg','B2','R',NULL,'18.2. Anti-emetics','43'),
('Lorazepam','Tablet','500 microgram','B2','R',NULL,'18.2. Anti-emetics','43'),
('Metoclopramide','Injection','5 mg/ml','C','R',NULL,'18.2. Anti-emetics','43'),
('Metoclopramide','Tablet','10 mg','B2','R',NULL,'18.2. Anti-emetics','43'),
('Ondansetron','Tablet','4 mg',NULL,'R',NULL,'18.2. Anti-emetics','43'),
('Ondansetron','Tablet','8 mg',NULL,'R',NULL,'18.2. Anti-emetics','43'),
('Promethazine Hydrochloride','Elixir','5 mg/ml','A','R',NULL,'18.2. Anti-emetics','43'),
('Promethazine Hydrochloride','Injection','25 mg/ml','B1','R',NULL,'18.2. Anti-emetics','43'),
('Promethazine Teoclate','Tablet','25 mg','M','R',NULL,'18.2. Anti-emetics','43'),
('Soothing Agent + Local Anaesthetic','Ointment','(blank)','M','R',NULL,'18.3. Anti-haemorrhoidal Drugs','43'),
('Soothing Agent + Local Anaesthetic','Suppository','(blank)','M','R',NULL,'18.3. Anti-haemorrhoidal Drugs','43'),
('Soothing Agent + Local Anaesthetic + Steroid','Ointment','(blank)','B1','R',NULL,'18.3. Anti-haemorrhoidal Drugs','43'),
('Soothing Agent + Local Anaesthetic + Steroid','Suppository','(blank)','B1','R',NULL,'18.3. Anti-haemorrhoidal Drugs','43'),
('Hyoscine-N-Butyl Bromide','Injection','20 mg/ml','M','R',NULL,'18.4. Anti-spasmodics','43'),
('Hyoscine-N-Butyl Bromide','Tablet','10 mg','M','R',NULL,'18.4. Anti-spasmodics','43'),
('Mebeverine','Tablet','135 mg','C','R',NULL,'18.4. Anti-spasmodics','43'),
('Bisacodyl','Suppository','10 mg','B1','R',NULL,'18.5. Cathartic Drugs','43'),
('Bisacodyl','Tablet','5 mg','B1','NR',NULL,'18.5. Cathartic Drugs','43'),
('Glycerol','Suppository','1 g',NULL,'R',NULL,'18.5. Cathartic Drugs','43'),
('Glycerol','Suppository','2 g',NULL,'R',NULL,'18.5. Cathartic Drugs','43'),
('Glycerol','Suppository','4 g',NULL,'R',NULL,'18.5. Cathartic Drugs','44'),
('Lactulose','Liquid','3.1 - 3.7 g/ml','C','R',NULL,'18.5. Cathartic Drugs','44'),
('Magnesium Sulphate','Salt','(blank)','B2','R',NULL,'18.5. Cathartic Drugs','44'),
('Milk of Magnesia','(blank)','(blank)',NULL,'R',NULL,'18.5. Cathartic Drugs','44'),
('Paraffin','Liquid','(blank)','A','R',NULL,'18.5. Cathartic Drugs','44'),
('Senna','Granules','(blank)','A','NR',NULL,'18.5. Cathartic Drugs','44'),
('Senna','Syrup','7.5 mg/5 ml','A','NR',NULL,'18.5. Cathartic Drugs','44'),
('Senna','Tablet','7.5 mg','A','NR',NULL,'18.5. Cathartic Drugs','44'),
('Oral Rehydration Salts','Sachet','(blank)','A','R',NULL,'Oral Replacement Solution','44'),
('Zinc','Tablet','10 mg','A','R',NULL,'Oral Replacement Solution','44'),
('Zinc','Tablet','20 mg','A','R',NULL,'Oral Replacement Solution','44'),
('Rifaximin','Tablet','200 mg',NULL,'NR',NULL,'18.6. Others','44'),
('Rifaximin','Tablet','550 mg',NULL,'NR',NULL,'18.6. Others','44'),
('Dexamethasone','Injection','4 mg/ml','M','R',NULL,'19.1. Adrenal Hormones and Synthetic substitutes','44'),
('Hydrocortisone','Injection','100 mg','M','R',NULL,'19.1. Adrenal Hormones and Synthetic substitutes','44'),
('Prednisolone','Tablet','5 mg','B2','R',NULL,'19.1. Adrenal Hormones and Synthetic substitutes','44'),
('Condoms (Female)','(blank)','(blank)','A','NR',NULL,'19.2. Contraceptives','44'),
('Condoms (Male)','(blank)','(blank)','A','NR',NULL,'19.2. Contraceptives','44'),
('Ethinylestradiol + Levonorgestrel','Injection','(blank)','PM','NR',NULL,'19.2. Contraceptives','44'),
('Ethinylestradiol + Levonorgestrel','Tablet','(blank)','PM','NR',NULL,'19.2. Contraceptives','44'),
('Ethinylestradiol + Norethisterone','Tablet','(blank)','PM','NR',NULL,'19.2. Contraceptives','45'),
('Medroxyprogesterone Acetate','Injection','150 mg','PM','NR',NULL,'19.2. Contraceptives','45'),
('Norethisterone','(blank)','(blank)',NULL,'NR',NULL,'19.2. Contraceptives','45'),
('Conjugated Oestrogen','Tablet','625 microgram','D','R',NULL,'19.3. Estrogens','45'),
('Conjugated Oestrogen','Vaginal Cream','625 microgram','D','R',NULL,'19.3. Estrogens','45'),
('Conjugated Oestrogen + Norgesterol','Tablet','626 microgram + 150 microgram','C','R',NULL,'19.3. Estrogens','45'),
('Glbenclamide','Tablet','5 mg','B1','R',NULL,'19.4. Insulins and other Anti-diabetic Drugs','45'),
('Gliclazide','Tablet','80 mg','C','R',NULL,'19.4. Insulins and other Anti-diabetic Drugs','45'),
('Glimerpiride','Tablet','1 mg','C','R',NULL,'19.4. Insulins and other Anti-diabetic Drugs','45'),
('Glimerpiride','Tablet','2 mg','C','R',NULL,'19.4. Insulins and other Anti-diabetic Drugs','45'),
('Glimerpiride','Tablet','4 mg','C','R',NULL,'19.4. Insulins and other Anti-diabetic Drugs','45'),
('Glucagon','Injection','1 mg','C','R',NULL,'19.4. Insulins and other Anti-diabetic Drugs','45'),
('Insulin Determir (Long acting)','Injection','100 units/ml','C','NR',NULL,'19.4. Insulins and other Anti-diabetic Drugs','45'),
('Insulin Glargine (Long acting)','Injection','100 units/ml','C','NR',NULL,'19.4. Insulins and other Anti-diabetic Drugs','45'),
('Insulin Lispro (Fast acting)','Injection','100 units/ml','C','NR',NULL,'19.4. Insulins and other Anti-diabetic Drugs','45'),
('Insulin Pre-mixed (30/70) HM','Injection','100 units/ml','C','R',NULL,'19.4. Insulins and other Anti-diabetic Drugs','45'),
('Insulin Soluble HM (Fast acting)','Injection','100 units/ml','C','R',NULL,'19.4. Insulins and other Anti-diabetic Drugs','45'),
('Metformin','Tablet','500 mg','B1','R',NULL,'19.4. Insulins and other Anti-diabetic Drugs','45'),
('NPH Insulin (Intermediate acting)','Injection','100 units/ml','C','R',NULL,'19.4. Insulins and other Anti-diabetic Drugs','45'),
('Pioglitazone','Tablet','15 mg','C','R',NULL,'19.4. Insulins and other Anti-diabetic Drugs','45'),
('Pioglitazone','Tablet','30 mg','C','R',NULL,'19.4. Insulins and other Anti-diabetic Drugs','46'),
('Saxagliptin','Tablet','2.5 mg',NULL,'R',NULL,'19.4. Insulins and other Anti-diabetic Drugs','46'),
('Sitagliptin','Tablet','100 mg',NULL,'R',NULL,'19.4. Insulins and other Anti-diabetic Drugs','46'),
('Sitagliptin','Tablet','25 mg',NULL,'R',NULL,'19.4. Insulins and other Anti-diabetic Drugs','46'),
('Tolbutamide','Tablet','500 mg','C','R',NULL,'19.4. Insulins and other Anti-diabetic Drugs','46'),
('Vildagliptin','Tablet','50 mg',NULL,'R',NULL,'19.4. Insulins and other Anti-diabetic Drugs','46'),
('Bromocriptine','Tablet','1.25 mg','D','R',NULL,'19.5. Other Endocrinological Drugs','46'),
('Bromocriptine','Tablet','2.5 mg','D','R',NULL,'19.5. Other Endocrinological Drugs','46'),
('Clomifene Citrate','Tablet','50 mg','D','NR',NULL,'19.6. Ovulation Inducers','46'),
('Medroxyprogesterone Acetate','Tablet','5 mg','D','R',NULL,'19.7. Progestogens','46'),
('Norethisterone','Tablet','5 mg','D','R',NULL,'19.7. Progestogens','46'),
('Carbimazole','Tablet','20 mg','C','R',NULL,'19.8. Thyroid hormones and Anti-thyroid Drugs','46'),
('Carbimazole','Tablet','5 mg','C','R',NULL,'19.8. Thyroid hormones and Anti-thyroid Drugs','46'),
('Levothyroxine','Tablet','100 microgram','C','R',NULL,'19.8. Thyroid hormones and Anti-thyroid Drugs','46'),
('Levothyroxine','Tablet','50 microgram','C','R',NULL,'19.8. Thyroid hormones and Anti-thyroid Drugs','46'),
('Propylthiouracil','Tablet','50 mg','D','R',NULL,'19.8. Thyroid hormones and Anti-thyroid Drugs','46'),
('Anti D Rh Immunoglobulin','Injection','250 units/ml','C','R',NULL,'20.1. Sera and Immunoglobulins','46'),
('Anti D Rh Immunoglobulin','Injection','750 units/ml','C','R',NULL,'20.1. Sera and Immunoglobulins','46'),
('Anti-Snake Serum (West African Polyvalent)','Injection','1500 IU/ml','B1','NR',NULL,'20.1. Sera and Immunoglobulins','46'),
('Antirabies Immunoglobulin','Injection','1000 IU/5 ml','B1','NR',NULL,'20.1. Sera and Immunoglobulins','47'),
('Diphtheria Antitoxin','Infusion','(blank)',NULL,'R',NULL,'20.1. Sera and Immunoglobulins','47'),
('Tetanus Immunoglobulin','Injection','250 IU/ml','M','R',NULL,'20.1. Sera and Immunoglobulins','47'),
('Tetanus Immunoglobulin','Injection','5000 IU/amp','M','R',NULL,'20.1. Sera and Immunoglobulins','47'),
('Tetanus Toxoid','Injection','40 IU (0.5 ml)','M','NR',NULL,'20.1. Sera and Immunoglobulins','47'),
('Meningococcal Vaccine','Injection','(blank)','B1','NR',NULL,'Vaccines for specific groups of individuals','47'),
('Pneumococcal Conjugate Vaccine 13 (PCV13)','Injection','(blank)',NULL,'NR',NULL,'Vaccines for specific groups of individuals','47'),
('Rabies Vaccine','Injection','(blank)','B1','NR',NULL,'Vaccines for specific groups of individuals','47'),
('Tetanus Toxoid','Injection','40 IU (0.5 ml)','M','NR',NULL,'Vaccines for specific groups of individuals','47'),
('Tetanus Vaccine','Injection','40 IU/5 ml','M','NR',NULL,'Vaccines for specific groups of individuals','47'),
('Yellow Fever Vaccine','Injection','(blank)','PM','NR',NULL,'Vaccines for specific groups of individuals','47'),
('Bacillus Calmette-Guerin (BCG) Vaccine','Injection','(blank)','PM','NR',NULL,'Vaccines for universal immunisation','47'),
('Five in One Vaccine (Diphtheria, Pertussis, Tetanus, Heamophilus influenzae b and Hepatitis B)','Injection','(blank)','PM','NR',NULL,'Vaccines for universal immunisation','47'),
('Hepatitis B Vaccine','Injection','(blank)','PM','NR',NULL,'Vaccines for universal immunisation','47'),
('Measles Vaccine','Injection','(blank)','PM','NR',NULL,'Vaccines for universal immunisation','47'),
('Poliomyelitis Vaccine','Oral Solution','(blank)','PM','NR',NULL,'Vaccines for universal immunisation','47'),
('Tetanus Vaccine','Injection','40 IU/5 ml','M','NR',NULL,'Vaccines for universal immunisation','47'),
('Yellow Fever Vaccine','Injection','(blank)','PM','NR',NULL,'Vaccines for universal immunisation','47'),
('Pegylated inteferon alfa-2a','Injection','180 microgram/ ml',NULL,'R',NULL,'20.3. Others','47'),
('Pegylated inteferon alfa-2b','Powder and solvent for injection','50 microgram',NULL,'R',NULL,'20.3. Others','48'),
('Pegylated inteferon alfa-2b','Powder and solvent for injection','80 microgram',NULL,'R',NULL,'20.3. Others','48'),
('Cyclobenzaprine','Tablet','(blank)',NULL,'R',NULL,'21. Muscle relaxants and Cholinesterase Inhibitors','48'),
('Tizanidine','Tablet','2 mg',NULL,'R',NULL,'21. Muscle relaxants and Cholinesterase Inhibitors','48'),
('Sodium Cromoglycate','Eye Drops','0.02','B1','NR',NULL,'22.1. Anti-allergic agents','48'),
('Chloramphenicol','Ear, Eye Drops','0.5%','A','(blank)',NULL,'22.2. Anti-infective agents','48'),
('Chloramphenicol','Eye Ointment','1%','A','(blank)',NULL,'22.2. Anti-infective agents','48'),
('Ciprofloxacin','Eye Drops','0.3%','B2','R',NULL,'22.2. Anti-infective agents','48'),
('Tetracycline','Eye Ointment','1%','M','R',NULL,'22.2. Anti-infective agents','48'),
('Corticosteroid + Antibiotic','Eye Drops','(blank)','C','R',NULL,'22.3. Anti-inflammatory agents','48'),
('Corticosteroid + Antibiotic','Eye Ointment','(blank)','C','R',NULL,'22.3. Anti-inflammatory agents','48'),
('Acetazolamide','Injection','500 mg','C','R',NULL,'22.4. Miotics and Drugs used in Glaucoma','48'),
('Acetazolamide','Tablet','250 mg','C','R',NULL,'22.4. Miotics and Drugs used in Glaucoma','48'),
('Betaxolol','Eye Drops','0.5%',NULL,'NR',NULL,'22.4. Miotics and Drugs used in Glaucoma','48'),
('Bimatoprost','Eye Drops','300 microgram/ ml','SM','NR',NULL,'22.4. Miotics and Drugs used in Glaucoma','48'),
('Latanoprost','Eye Drops','50 microgram/ ml','SM','NR',NULL,'22.4. Miotics and Drugs used in Glaucoma','48'),
('Levobunolol','Eye Drops','0.5%',NULL,'NR',NULL,'22.4. Miotics and Drugs used in Glaucoma','48'),
('Pilocarpine','Eye Drops','0.02','C','R',NULL,'22.4. Miotics and Drugs used in Glaucoma','49'),
('Pilocarpine','Eye Drops','0.04','C','R',NULL,'22.4. Miotics and Drugs used in Glaucoma','49'),
('Pilocarpine','Eye Drops','1%','C','R',NULL,'22.4. Miotics and Drugs used in Glaucoma','49'),
('Timolol Maleate','Eye Drops','0.5%','C','R',NULL,'22.4. Miotics and Drugs used in Glaucoma','49'),
('Travoprost','Eye Drops','40 microgram/ ml',NULL,'NR',NULL,'22.4. Miotics and Drugs used in Glaucoma','49'),
('Phenylephrine','Eye Drops','10%','SM','NR',NULL,'22.5. Mydriatics and Cycloplegics','49'),
('Phenylephrine','Eye Drops','2.5%','SM','NR',NULL,'22.5. Mydriatics and Cycloplegics','49'),
('Fluorescein','Eye Drops','(blank)','C','NR',NULL,'22.6. Ophthalmic Drugs','49'),
('Brimornidine','(blank)','1 mg/ml',NULL,'NR',NULL,'22.7. Others','49'),
('Brimornidine','(blank)','1.5 mg/ml',NULL,'NR',NULL,'22.7. Others','49'),
('Brinzolamide','Eye Drops','10 mg/ml',NULL,'NR',NULL,'22.7. Others','49'),
('Dorzolamide','Eye Drops','20 mg/ml',NULL,'NR',NULL,'22.7. Others','49'),
('Hydroxymethyl Cellulose','Eye Drops','0.3%',NULL,'R',NULL,'22.7. Others','49'),
('Polyvinyl Alcohol','Eye Drops','0.014',NULL,'R',NULL,'22.7. Others','49'),
('Polyvinyl Alcohol','Eye Drops','0.02',NULL,'R',NULL,'22.7. Others','49'),
('Sodium Chloride','Solution','0.009','A','R',NULL,'22.7. Others','49'),
('Proparacaine Hydrochloride','Eye Drops','0.5%',NULL,'R',NULL,'22.8. Topical Anaesthetics','49'),
('Tetracaine Hydrochloride','Eye Drops','0.5%',NULL,'R',NULL,'22.8. Topical Anaesthetics','49'),
('Chlorhexidine','Mouthwash','0.12%','A','R',NULL,'23.1. Drugs for Dentistry','49'),
('Lidocaine','Gel','0.02','M','R',NULL,'23.1. Drugs for Dentistry','49'),
('Lidocaine + Adrenaline','Cartridge','20 mg/ ml + [1:80 000/1:100 000]','B2','R',NULL,'23.1. Drugs for Dentistry','50'),
('Miconazole','Oral Gel','24 mg/ml','B1','R',NULL,'23.1. Drugs for Dentistry','50'),
('Nystatin','Oral Suspension','100 000 IU','B1','R',NULL,'23.1. Drugs for Dentistry','50'),
('Povidone Iodine','Mouthwash','1%','A','R',NULL,'23.1. Drugs for Dentistry','50'),
('Adrenaline (Epinephrine)','As nose pack','1 mg /ml (1:1000)','A','R',NULL,'23.2. Drugs for Ear, Nose and Throat','50'),
('Ciprofloxacin','Ear Drops','0.3%','B2','R',NULL,'23.2. Drugs for Ear, Nose and Throat','50'),
('Ephedrine Hydrochloride','Nasal Drops','0.5%','A','R',NULL,'23.2. Drugs for Ear, Nose and Throat','50'),
('Ephedrine Hydrochloride','Nasal Drops','1%','A','R',NULL,'23.2. Drugs for Ear, Nose and Throat','50'),
('Gentamicin','Ear Drops','0.3%','B1','R',NULL,'23.2. Drugs for Ear, Nose and Throat','50'),
('Neomycin + Hydrocortisone','Nasal Drops','0.5% + 1.5%',NULL,'R',NULL,'23.2. Drugs for Ear, Nose and Throat','50'),
('Oxymetazoline','Nasal Spray','0.3%',NULL,'R',NULL,'23.2. Drugs for Ear, Nose and Throat','50'),
('Sodium Chloride','Nasal Drops','0.009','A','R',NULL,'23.2. Drugs for Ear, Nose and Throat','50'),
('Xylometazoline','Nasal Spray','0.001',NULL,'R',NULL,'23.2. Drugs for Ear, Nose and Throat','50'),
('Xylometazoline','Nasal Spray','0.05%',NULL,'R',NULL,'23.2. Drugs for Ear, Nose and Throat','50'),
('Abacavir + Lamivudine','Tablet','60 mg + 30 mg',NULL,'NR',NULL,'23.3. Drugs for HIV/AIDS','50'),
('Abacavir + Lamivudine','Tablet','600 mg + 300 mg',NULL,'NR',NULL,'23.3. Drugs for HIV/AIDS','50'),
('Atazanavir + Ritonavir','Tablet','300 mg + 100 mg',NULL,'NR',NULL,'23.3. Drugs for HIV/AIDS','50'),
('Efavirenz','Tablet','200 mg','PM','NR',NULL,'23.3. Drugs for HIV/AIDS','50'),
('Efavirenz','Tablet','50 mg','PM','NR',NULL,'23.3. Drugs for HIV/AIDS','50'),
('Efavirenz','Tablet','600 mg','PM','NR',NULL,'23.3. Drugs for HIV/AIDS','50'),
('Emtricitabine + Tenofovir','Tablet','200 mg + 300 mg',NULL,'NR',NULL,'23.3. Drugs for HIV/AIDS','50'),
('Emtricitabine + Tenofovir + Efavirenz','Tablet','200 mg + 300 mg + 600 mg',NULL,'NR',NULL,'23.3. Drugs for HIV/AIDS','51'),
('Lamivudine','Tablet','150 mg','PM','NR',NULL,'23.3. Drugs for HIV/AIDS','51'),
('Lamivudine + Tenofovir','Tablet','150 mg + 300 mg',NULL,'NR',NULL,'23.3. Drugs for HIV/AIDS','51'),
('Lamivudine + Zidovudine + Nevirapine','Tablet','150 mg + 300 mg + 200 mg',NULL,'NR',NULL,'23.3. Drugs for HIV/AIDS','51'),
('Lopinavir + Ritonavir','Tablet','100 mg + 25 mg','PM','NR',NULL,'23.3. Drugs for HIV/AIDS','51'),
('Lopinavir + Ritonavir','Tablet','200 mg + 50 mg','PM','NR',NULL,'23.3. Drugs for HIV/AIDS','51'),
('Nevirapine','Dispersible Tablet','50 mg','PM','NR',NULL,'23.3. Drugs for HIV/AIDS','51'),
('Nevirapine','Suspension','10 mg/ml','PM','NR',NULL,'23.3. Drugs for HIV/AIDS','51'),
('Nevirapine','Tablet','200 mg','PM','NR',NULL,'23.3. Drugs for HIV/AIDS','51'),
('Tenofovir + Lamivudine + Efavirenz','Tablet','300 mg + 300 mg + 600 mg',NULL,'NR',NULL,'23.3. Drugs for HIV/AIDS','51'),
('Tenofovir Disoproxil Fumarate','Tablet','300 mg','PM','NR',NULL,'23.3. Drugs for HIV/AIDS','51'),
('Zidovudine','Syrup','10 mg/ml','PM','NR',NULL,'23.3. Drugs for HIV/AIDS','51'),
('Zidovudine','Tablet','300 mg','PM','NR',NULL,'23.3. Drugs for HIV/AIDS','51'),
('Zidovudine + Lamivudine','Tablet','300 mg + 150 mg','PM','NR',NULL,'23.3. Drugs for HIV/AIDS','51'),
('Zidovudine + Lamivudine','Tablet','60 mg + 30 mg','PM','NR',NULL,'23.3. Drugs for HIV/AIDS','51'),
('Zidovudine + Lamivudine + Efavirenz','Tablet','300 mg + 150 mg + 600 mg',NULL,'NR',NULL,'23.3. Drugs for HIV/AIDS','51'),
('Alfuzocin','Tablet','(blank)',NULL,'R',NULL,'23.4. Drugs for Urology','51'),
('Finasteride','Tablet','5 mg','SM','R',NULL,'23.4. Drugs for Urology','51'),
('Prostagladin E1','Tablet','(blank)',NULL,'R',NULL,'23.4. Drugs for Urology','51'),
('Sildenafil Citrate','Tablet','(blank)',NULL,'R',NULL,'23.4. Drugs for Urology','51'),
('Tadalafil','Tablet','(blank)',NULL,'R',NULL,'23.4. Drugs for Urology','51'),
('Tamsulosin','Capsule','400 microgram','SM','R',NULL,'23.4. Drugs for Urology','52'),
('Terazosin','Tablet','2 mg','SM','R',NULL,'23.4. Drugs for Urology','52'),
('Terazosin','Tablet','5 mg','SM','R',NULL,'23.4. Drugs for Urology','52'),
('Verdanafil','Tablet','(blank)',NULL,'R',NULL,'23.4. Drugs for Urology','52'),
('Alendronate','Injection','(blank)',NULL,'R',NULL,'23.5. Drugs used in Orthopaedics','52'),
('Calcitonin','(blank)','(blank)',NULL,'R',NULL,'23.5. Drugs used in Orthopaedics','52'),
('Denosumab','Injection','60 mg/ml',NULL,'R',NULL,'23.5. Drugs used in Orthopaedics','52'),
('Denosumab','Injection','70 mg/ml',NULL,'R',NULL,'23.5. Drugs used in Orthopaedics','52'),
('Intravenous Immunoglob- ulin (IVIg)','Injection','(blank)',NULL,'R',NULL,'23.5. Drugs used in Orthopaedics','52'),
('Pamidronate','Injection','15 mg/ml',NULL,'R',NULL,'23.5. Drugs used in Orthopaedics','52'),
('Pamidronate','Injection','6 mg/ml',NULL,'R',NULL,'23.5. Drugs used in Orthopaedics','52'),
('Phosphocitrate','(blank)','(blank)',NULL,'R',NULL,'23.5. Drugs used in Orthopaedics','52'),
('Probenecid','(blank)','(blank)',NULL,'R',NULL,'23.5. Drugs used in Orthopaedics','52'),
('Strontium Ranelate','Granule Sachets','2 g',NULL,'R',NULL,'23.5. Drugs used in Orthopaedics','52'),
('Teriparatide','(blank)','(blank)',NULL,'R',NULL,'23.5. Drugs used in Orthopaedics','52'),
('Triamcinolone','Injection','(blank)',NULL,'R',NULL,'23.5. Drugs used in Orthopaedics','52'),
('Entecavir','Tablet','50 microgram/ ml',NULL,'R',NULL,'23.6. Nucleoside analogues','52'),
('Entecavir','Tablet','500 microgram',NULL,'R',NULL,'23.6. Nucleoside analogues','52'),
('Ribavirin','Tablet','200 mg',NULL,'R',NULL,'23.6. Nucleoside analogues','52'),
('Ribavirin','Tablet','400 mg',NULL,'R',NULL,'23.6. Nucleoside analogues','52'),
('Salbutamol','Tablet','4 mg','M','R',NULL,'24.1. Anti-oxytocics','52'),
('Salbutamol','Injection','500 microgram/ ml','B2','R',NULL,'24.1. Anti-oxytocics','53'),
('Ergometrine','Injection','200 microgram/ ml','M','R',NULL,'24.2. Oxytocics','53'),
('Ergometrine','Injection','500 microgram/ ml','M','R',NULL,'24.2. Oxytocics','53'),
('Ergometrine','Tablet','200 microgram','M','R',NULL,'24.2. Oxytocics','53'),
('Ergometrine','Tablet','500 microgram','M','R',NULL,'24.2. Oxytocics','53'),
('Mifepristone','Tablet','600 microgram','SM','NR',NULL,'24.2. Oxytocics','53'),
('Misoprostol','Tablet','100 microgram','PM','NR',NULL,'24.2. Oxytocics','53'),
('Misoprostol','Tablet','200 microgram','PM','NR',NULL,'24.2. Oxytocics','53'),
('Misoprostol','Tablet','25 microgram','M','NR',NULL,'24.2. Oxytocics','53'),
('Misoprostol','Tablet','50 microgram','M','NR',NULL,'24.2. Oxytocics','53'),
('Misoprostol','Vaginal Tablet','200 microgram','PM','R',NULL,'24.2. Oxytocics','53'),
('Oxytocin','Injection','10 units/ml','M','R',NULL,'24.2. Oxytocics','53'),
('Oxytocin','Injection','5 units/ml','M','R',NULL,'24.2. Oxytocics','53'),
('Atropine','Injection','0.6 mg/ml','B2','R',NULL,'25. Pre-operative medications and Sedation for short-term procedures','53'),
('Diazepam','Injection','5 mg/ml','B1','R',NULL,'25. Pre-operative medications and Sedation for short-term procedures','53'),
('Lorazepam','Injection','4 mg/ml','D','R',NULL,'25. Pre-operative medications and Sedation for short-term procedures','53'),
('Lorazepam','Tablet','1 mg','B2','R',NULL,'25. Pre-operative medications and Sedation for short-term procedures','53'),
('Lorazepam','Tablet','2 mg','B2','R',NULL,'25. Pre-operative medications and Sedation for short-term procedures','53'),
('Midazolam','Injection','1 mg/ml','C','R',NULL,'25. Pre-operative medications and Sedation for short-term procedures','54'),
('Midazolam','Tablet','15 mg','B2','R',NULL,'25. Pre-operative medications and Sedation for short-term procedures','54'),
('Alprazolam','Tablet','(blank)',NULL,'R',NULL,'26. Psychotherapeutic Drugs','54'),
('Amitriptyline','Tablet','10 mg','B1','R',NULL,'26. Psychotherapeutic Drugs','54'),
('Amitriptyline','Tablet','25 mg','B2','R',NULL,'26. Psychotherapeutic Drugs','54'),
('Amitriptyline','Tablet','50 mg','B1','R',NULL,'26. Psychotherapeutic Drugs','54'),
('Atomoxetine','Tablet','(blank)',NULL,'R',NULL,'26. Psychotherapeutic Drugs','54'),
('Benzatropine','Injection','1 mg/ml','C','R',NULL,'26. Psychotherapeutic Drugs','54'),
('Benzatropine','Tablet','2 mg','C','R',NULL,'26. Psychotherapeutic Drugs','54'),
('Biperiden','Injection','5 mg/ml','C','NR',NULL,'26. Psychotherapeutic Drugs','54'),
('Biperiden','Tablet','2 mg','C','NR',NULL,'26. Psychotherapeutic Drugs','54'),
('Chloral Hydrate','Oral Solution','28.66 mg/ml',NULL,'R',NULL,'26. Psychotherapeutic Drugs','54'),
('Chloral Hydrate','Tablet','707 mg',NULL,'R',NULL,'26. Psychotherapeutic Drugs','54'),
('Chlordiazepoxide Hydrochloride','Tablet','5 mg','C','R',NULL,'26. Psychotherapeutic Drugs','54'),
('Chlorpromazine','Injection','25 mg/ml','B2','R',NULL,'26. Psychotherapeutic Drugs','54'),
('Chlorpromazine','Tablet','100 mg','B1','R',NULL,'26. Psychotherapeutic Drugs','54'),
('Chlorpromazine','Tablet','25 mg','B1','R',NULL,'26. Psychotherapeutic Drugs','54'),
('Chlorpromazine','Tablet','50 mg','B1','R',NULL,'26. Psychotherapeutic Drugs','54'),
('Citalopram','Tablet','10 mg',NULL,'R',NULL,'26. Psychotherapeutic Drugs','54'),
('Citalopram','Tablet','20 mg',NULL,'R',NULL,'26. Psychotherapeutic Drugs','54'),
('Citalopram','Tablet','40 mg',NULL,'R',NULL,'26. Psychotherapeutic Drugs','54'),
('Diazepam','Injection','5 mg/ml','B1','R',NULL,'26. Psychotherapeutic Drugs','54'),
('Diazepam','Tablet','10 mg','M','R',NULL,'26. Psychotherapeutic Drugs','54'),
('Diazepam','Tablet','5 mg','M','R',NULL,'26. Psychotherapeutic Drugs','54'),
('Duloxetine Hydrochloride','Tablet','20 mg',NULL,'R',NULL,'26. Psychotherapeutic Drugs','54'),
('Duloxetine Hydrochloride','Tablet','30 mg',NULL,'R',NULL,'26. Psychotherapeutic Drugs','54'),
('Fluoxetine','Capsule','20 mg','C','R',NULL,'26. Psychotherapeutic Drugs','54'),
('Flupenthixol Decanoate','Injection','20 mg/ml',NULL,'R',NULL,'26. Psychotherapeutic Drugs','55'),
('Fluphenazine Decanoate','Injection','25 mg/ml','SM','R',NULL,'26. Psychotherapeutic Drugs','55'),
('Haloperidol','Injection','5 mg','SM','R',NULL,'26. Psychotherapeutic Drugs','55'),
('Haloperidol','Tablet','10 mg','C','R',NULL,'26. Psychotherapeutic Drugs','55'),
('Haloperidol','Tablet','5 mg','C','R',NULL,'26. Psychotherapeutic Drugs','55'),
('Imipramine','Tablet','25 mg','C','R',NULL,'26. Psychotherapeutic Drugs','55'),
('Lamotrigine','Tablet','100 mg',NULL,'R',NULL,'26. Psychotherapeutic Drugs','55'),
('Lamotrigine','Tablet','25 mg',NULL,'R',NULL,'26. Psychotherapeutic Drugs','55'),
('Lamotrigine','Tablet','50 mg',NULL,'R',NULL,'26. Psychotherapeutic Drugs','55'),
('Lithium Carbonate','Tablet (slow release)','200 mg','SM','R',NULL,'26. Psychotherapeutic Drugs','55'),
('Lithium Carbonate','Tablet (slow release)','500 mg','SM','R',NULL,'26. Psychotherapeutic Drugs','55'),
('Lorazepam','Tablet','2 mg','B2','R',NULL,'26. Psychotherapeutic Drugs','55'),
('Melatonin','Tablet (Modified release)','2 mg',NULL,'R',NULL,'26. Psychotherapeutic Drugs','55'),
('Methylphenidate Hydrochloride','Tablet','5 mg','SM','R',NULL,'26. Psychotherapeutic Drugs','55'),
('Olanzapine','Injection','5 mg/ml','SM','R',NULL,'26. Psychotherapeutic Drugs','55'),
('Olanzapine','Tablet','10 mg','SM','R',NULL,'26. Psychotherapeutic Drugs','55'),
('Olanzapine','Tablet','5 mg','SM','R',NULL,'26. Psychotherapeutic Drugs','55'),
('Risperidone','Tablet','1 mg','SM','R',NULL,'26. Psychotherapeutic Drugs','55'),
('Risperidone','Tablet','2 mg','SM','R',NULL,'26. Psychotherapeutic Drugs','55'),
('Risperidone','Tablet','500 microgram','SM','R',NULL,'26. Psychotherapeutic Drugs','55'),
('Sertraline','Tablet','100 mg','SM','R',NULL,'26. Psychotherapeutic Drugs','55'),
('Sertraline','Tablet','50 mg','SM','R',NULL,'26. Psychotherapeutic Drugs','55'),
('Sodium Valproate','Tablet','200 mg','D','R',NULL,'26. Psychotherapeutic Drugs','55'),
('Triazolam','Tablet','(blank)',NULL,'R',NULL,'26. Psychotherapeutic Drugs','55'),
('Trihexyphenidyl','Oral Solution','1 mg/ml','C','R',NULL,'26. Psychotherapeutic Drugs','55'),
('Trihexyphenidyl','Tablet','2 mg','C','R',NULL,'26. Psychotherapeutic Drugs','56'),
('Trihexyphenidyl','Tablet','5 mg','C','R',NULL,'26. Psychotherapeutic Drugs','56'),
('Mist. Potassium Citrate','Solution','(blank)',NULL,'R',NULL,'27.1. Oral preparations','56'),
('Oral Rehydration Salts','Sachet','(blank)','A','R',NULL,'27.1. Oral preparations','56'),
('Potassium Chloride','Tablet (Enteric Coated)','600 mg','B1','R',NULL,'27.1. Oral preparations','56'),
('Badoe''s Solution','Injection','1000 ml','B1','R',NULL,'27.2. Parenteral solutions','56'),
('Calcium Gluconate','Injection','10% (100 mg/ml)','B2','R',NULL,'27.2. Parenteral solutions','56'),
('Cholera Replacement Fluid','Injection','(5:4:1)','B1','R',NULL,'27.2. Parenteral solutions','56'),
('Darrow''s Solution','Half-strenght','250 ml','B1','R',NULL,'27.2. Parenteral solutions','56'),
('Dextrose','Infusion','10% (250 ml)','B1','R',NULL,'27.2. Parenteral solutions','56'),
('Dextrose','Infusion','10% (500 ml)','B1','R',NULL,'27.2. Parenteral solutions','56'),
('Dextrose','Infusion','20% (250 ml)','C','R',NULL,'27.2. Parenteral solutions','56'),
('Dextrose','Infusion','5% (250 ml)','M','R',NULL,'27.2. Parenteral solutions','56'),
('Dextrose','Infusion','5% (500 ml)','M','R',NULL,'27.2. Parenteral solutions','56'),
('Dextrose','Infusion','50% (50 ml)','B2','R',NULL,'27.2. Parenteral solutions','56'),
('Dextrose in Sodium Chloride','Infusion','10% in 0.18% (250 ml)','C','R',NULL,'27.2. Parenteral solutions','56'),
('Dextrose in Sodium Chloride','Infusion','4.3% in 0.18% (250 ml)','M','R',NULL,'27.2. Parenteral solutions','56'),
('Dextrose in Sodium Chloride','Infusion','5% in 0.9% (500 ml)','M','R',NULL,'27.2. Parenteral solutions','56'),
('Potassium Chloride','Injection','20 mEq/10 ml','C','R',NULL,'27.2. Parenteral solutions','56'),
('Ringers Lactate','Infusion','500 ml','M','R',NULL,'27.2. Parenteral solutions','56'),
('Sodium Bicarbonate','Injection','0.084','C','R',NULL,'27.2. Parenteral solutions','57'),
('Sodium Chloride','Injection','0.45% (250 ml)','B1','R',NULL,'27.2. Parenteral solutions','57'),
('Sodium Chloride','Injection','0.9% (250 ml)','M','NR',NULL,'27.2. Parenteral solutions','57'),
('Sodium Chloride','Injection','0.9% (500 ml)','M','R',NULL,'27.2. Parenteral solutions','57'),
('Sodium Chloride + Potassium Chloride','Injection','0.9% + 20 mMol (500 ml)','SM','NR',NULL,'27.2. Parenteral solutions','57'),
('Water for Injection','Injection','(blank)','A','R',NULL,'27.3. Miscellaneous','57'),
('Calciferol','Injection','(blank)','D','R',NULL,'28. Vitamins and Minerals','57'),
('Calciferol','Tablet','10 000 units','D','R',NULL,'28. Vitamins and Minerals','57'),
('Calcium','Tablet','(blank)','M','R',NULL,'28. Vitamins and Minerals','57'),
('Calcium + Vitamin D','Tablet','97 mg + 10 microgram','M','R',NULL,'28. Vitamins and Minerals','57'),
('Calcium Gluconate','Injection','100 mg/ml','B2','R',NULL,'28. Vitamins and Minerals','57'),
('Multivitamin','Syrup','(blank)','A','R',NULL,'28. Vitamins and Minerals','57'),
('Multivitamin','Tablet','(blank)','A','R',NULL,'28. Vitamins and Minerals','57'),
('Pyridoxine','Tablet','100 mg','B2','R',NULL,'28. Vitamins and Minerals','57'),
('Pyridoxine','Tablet','50 mg','B2','R',NULL,'28. Vitamins and Minerals','57'),
('Retinol','Capsule','100 000 IU','A','R',NULL,'28. Vitamins and Minerals','57'),
('Retinol','Capsule','200 000 IU','A','R',NULL,'28. Vitamins and Minerals','57'),
('Thiamine','Injection','100 mg','C','R',NULL,'28. Vitamins and Minerals','57'),
('Thiamine','Tablet','100 mg','C','R',NULL,'28. Vitamins and Minerals','57'),
('Thiamine','Tablet','25 mg','C','R',NULL,'28. Vitamins and Minerals','57'),
('Thiamine','Tablet','50 mg','C','R',NULL,'28. Vitamins and Minerals','57'),
('Vitamin B-Compound','Injection','(High potency)',NULL,'R',NULL,'28. Vitamins and Minerals','57'),
('Vitamin C','Tablet','(blank)',NULL,'R',NULL,'28. Vitamins and Minerals','57');
